import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router';
import {
  QueryTypesSandboxPage,
  parseQueryTypeParameters,
  queryParamsToActionParams,
} from '../QueryTypesSandboxPage';
import * as ontologiesApi from '../../../api/ontologies';
import type { QueryType } from '../../../api/types';

const topCustomers: QueryType = {
  rid: 'ri.ontology.main.querytype.top',
  apiName: 'topCustomers',
  displayName: 'Top Customers',
  description: 'Customers ordered by revenue',
  status: 'ACTIVE',
  parameters: [
    { id: 'limit', type: 'integer', required: true, description: 'Result limit' },
  ],
  output: {},
  query: {},
};

const recentOrders: QueryType = {
  rid: 'ri.ontology.main.querytype.recent',
  apiName: 'recentOrders',
  displayName: 'Recent Orders',
  status: 'EXPERIMENTAL',
  parameters: [],
  output: {},
  query: {},
};

function renderPage() {
  const qc = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  return render(
    <QueryClientProvider client={qc}>
      <MemoryRouter initialEntries={['/queries/northwind']}>
        <Routes>
          <Route
            path="/queries/:ontology"
            element={<QueryTypesSandboxPage />}
          />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>,
  );
}

describe('parseQueryTypeParameters', () => {
  it('parses an array payload', () => {
    const got = parseQueryTypeParameters([
      { id: 'limit', type: 'integer', required: true },
      { id: 'name', type: 'string' },
    ]);
    expect(got).toEqual([
      {
        id: 'limit',
        type: 'integer',
        required: true,
        description: undefined,
      },
      {
        id: 'name',
        type: 'string',
        required: false,
        description: undefined,
      },
    ]);
  });

  it('parses a JSON-encoded string payload', () => {
    const got = parseQueryTypeParameters(
      '[{"id":"q","type":"string","required":true}]',
    );
    expect(got).toHaveLength(1);
    expect(got[0]).toMatchObject({ id: 'q', type: 'string', required: true });
  });

  it('returns [] for malformed JSON', () => {
    expect(parseQueryTypeParameters('not json')).toEqual([]);
  });

  it('drops entries without an id', () => {
    const got = parseQueryTypeParameters([
      { id: 'a', type: 'string' },
      { type: 'string' },
      { id: '', type: 'string' },
    ]);
    expect(got.map((p) => p.id)).toEqual(['a']);
  });
});

describe('queryParamsToActionParams', () => {
  it('lifts flat type into nested dataType.type', () => {
    const got = queryParamsToActionParams([
      { id: 'limit', type: 'integer', required: true, description: 'Cap' },
    ]);
    expect(got).toEqual({
      limit: {
        dataType: { type: 'integer' },
        required: true,
        description: 'Cap',
      },
    });
  });
});

describe('QueryTypesSandboxPage', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('renders the list and counts QueryTypes', async () => {
    vi.spyOn(ontologiesApi, 'listQueryTypes').mockResolvedValue([
      topCustomers,
      recentOrders,
    ]);
    renderPage();

    expect(await screen.findByTestId('query-types-sandbox-page')).toBeTruthy();
    const rows = await screen.findAllByTestId('query-type-row');
    expect(rows).toHaveLength(2);
    expect(screen.getByTestId('query-types-count')).toHaveTextContent(
      '2 QueryTypes',
    );
  });

  it('shows an empty state when no QueryTypes exist', async () => {
    vi.spyOn(ontologiesApi, 'listQueryTypes').mockResolvedValue([]);
    renderPage();

    await waitFor(() =>
      expect(screen.getByTestId('query-types-sandbox-empty')).toBeTruthy(),
    );
  });

  it('renders the parameter form from the selected QueryType schema and executes against the API', async () => {
    vi.spyOn(ontologiesApi, 'listQueryTypes').mockResolvedValue([
      topCustomers,
    ]);
    const executeSpy = vi
      .spyOn(ontologiesApi, 'executeQueryType')
      .mockResolvedValue({ value: { customers: [], totalCount: 0 } });
    renderPage();

    // Pick the QueryType from the rail.
    const selectBtn = await screen.findByTestId(
      'query-type-select-topCustomers',
    );
    fireEvent.click(selectBtn);

    // The integer-typed `limit` field comes from the parameter schema —
    // the form is auto-generated by walking parameters and dispatching on
    // dataType.type.
    const limitInput = (await screen.findByLabelText(
      /^limit/i,
    )) as HTMLInputElement;
    expect(limitInput.type).toBe('number');
    fireEvent.change(limitInput, { target: { value: '3' } });

    fireEvent.click(screen.getByTestId('query-type-execute-button'));

    await waitFor(() =>
      expect(executeSpy).toHaveBeenCalledWith('northwind', 'topCustomers', {
        limit: 3,
      }),
    );

    // The result panel shows the JSON view + the table view (tab switch).
    await screen.findByTestId('query-result-panel');
    fireEvent.click(screen.getByTestId('query-result-tab-json'));
    expect(screen.getByTestId('query-result-json')).toHaveTextContent(
      'totalCount',
    );
  });
});
