import { useState, useRef, useEffect } from 'react';
import type { ObjectType } from '../../api/types';
import type { CreateLinkTypeInput } from '../../api/admin';

interface LinkTypeFormProps {
  onSubmit: (values: CreateLinkTypeInput) => void;
  objectTypes: ObjectType[];
  isLoading: boolean;
}

const cardinalityHelp: Record<CreateLinkTypeInput['cardinality'], string> = {
  ONE_TO_ONE: '每个源对象关联唯一的目标对象',
  ONE_TO_MANY: '一个源对象可关联多个目标对象（最常用）',
  MANY_TO_MANY: '双方都可关联多个对象',
};

function capitalize(s: string): string {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function LinkTypeForm({ onSubmit, objectTypes, isLoading }: LinkTypeFormProps) {
  const [apiName, setApiName] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [sourceObjectType, setSourceObjectType] = useState('');
  const [targetObjectType, setTargetObjectType] = useState('');
  const [cardinality, setCardinality] = useState<CreateLinkTypeInput['cardinality']>('ONE_TO_MANY');

  // Track whether the user has manually overridden auto-generated fields
  const apiNameAutoGenerated = useRef(true);
  const displayNameAutoGenerated = useRef(true);

  useEffect(() => {
    const source = objectTypes.find((ot) => ot.rid === sourceObjectType);
    const target = objectTypes.find((ot) => ot.rid === targetObjectType);

    if (source && target) {
      if (apiNameAutoGenerated.current) {
        setApiName(source.apiName + capitalize(target.apiName));
      }
      if (displayNameAutoGenerated.current) {
        setDisplayName(`${source.displayName} → ${target.displayName}`);
      }
    }
  }, [sourceObjectType, targetObjectType, objectTypes]);

  function handleApiNameChange(value: string) {
    apiNameAutoGenerated.current = false;
    setApiName(value);
  }

  function handleDisplayNameChange(value: string) {
    displayNameAutoGenerated.current = false;
    setDisplayName(value);
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    onSubmit({
      apiName,
      displayName,
      objectTypeApiName: sourceObjectType,
      linkedObjectTypeApiName: targetObjectType,
      cardinality,
    });
  }

  const inputClass =
    'bg-bg-tertiary border border-border rounded px-3 py-2 text-sm text-text-primary font-mono focus:border-accent-cyan focus:outline-none';
  const labelClass = 'text-xs text-text-secondary font-sans mb-1';

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-4">
      <div className="flex flex-col">
        <label className={labelClass}>Source Object Type</label>
        <select
          value={sourceObjectType}
          onChange={(e) => setSourceObjectType(e.target.value)}
          required
          className={inputClass}
        >
          <option value="">Select source...</option>
          {objectTypes.map((ot) => (
            <option key={ot.rid} value={ot.rid}>
              {ot.displayName} ({ot.apiName})
            </option>
          ))}
        </select>
      </div>

      <div className="flex flex-col">
        <label className={labelClass}>Target Object Type</label>
        <select
          value={targetObjectType}
          onChange={(e) => setTargetObjectType(e.target.value)}
          required
          className={inputClass}
        >
          <option value="">Select target...</option>
          {objectTypes.map((ot) => (
            <option key={ot.rid} value={ot.rid}>
              {ot.displayName} ({ot.apiName})
            </option>
          ))}
        </select>
      </div>

      <div className="flex flex-col">
        <label className={labelClass}>API Name</label>
        <input
          type="text"
          value={apiName}
          onChange={(e) => handleApiNameChange(e.target.value)}
          required
          className={inputClass}
          placeholder="employeeDepartment"
        />
      </div>

      <div className="flex flex-col">
        <label className={labelClass}>Display Name</label>
        <input
          type="text"
          value={displayName}
          onChange={(e) => handleDisplayNameChange(e.target.value)}
          required
          className={inputClass}
          placeholder="Employee → Department"
        />
      </div>

      <div className="flex flex-col">
        <label className={labelClass}>Cardinality</label>
        <select
          value={cardinality}
          onChange={(e) => setCardinality(e.target.value as CreateLinkTypeInput['cardinality'])}
          className={inputClass}
        >
          <option value="ONE_TO_ONE">ONE_TO_ONE</option>
          <option value="ONE_TO_MANY">ONE_TO_MANY</option>
          <option value="MANY_TO_MANY">MANY_TO_MANY</option>
        </select>
        <span className="text-xs text-text-secondary mt-1">{cardinalityHelp[cardinality]}</span>
      </div>

      <button
        type="submit"
        disabled={isLoading}
        className="bg-accent-cyan text-bg-primary px-4 py-2 rounded text-sm font-medium hover:bg-accent-cyan/80 disabled:opacity-50"
      >
        {isLoading ? 'Creating...' : 'Create Link Type'}
      </button>
    </form>
  );
}
