package sdkgen

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/liyang/weave/pkg/types"
)

type tsGenerator struct{}

func (g *tsGenerator) Language() string { return "ts" }

func (g *tsGenerator) Generate(_ context.Context, schema OntologySchema) ([]GeneratedFile, error) {
	var files []GeneratedFile

	models, err := g.generateModels(schema)
	if err != nil {
		return nil, fmt.Errorf("generate models: %w", err)
	}
	files = append(files, GeneratedFile{Path: "src/models.ts", Content: models})

	client, err := g.generateClient(schema)
	if err != nil {
		return nil, fmt.Errorf("generate client: %w", err)
	}
	files = append(files, GeneratedFile{Path: "src/client.ts", Content: client})

	files = append(files, GeneratedFile{Path: "src/index.ts", Content: g.generateIndex(schema)})
	files = append(files, GeneratedFile{Path: "package.json", Content: g.generatePackageJSON(schema)})
	files = append(files, GeneratedFile{Path: "tsconfig.json", Content: g.generateTSConfig()})

	files = appendVersionFiles(files, schema, g.Language())
	return files, nil
}

func (g *tsGenerator) generateModels(schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Auto-generated by Weave SDK Generator — do not edit.\n\n")

	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "export interface %s {\n", ot.APIName)
		for _, p := range ot.Properties {
			fmt.Fprintf(&buf, "  %s: %s;\n", p.APIName, resolveTSType(p.BaseType, p.IsArray))
		}
		buf.WriteString("}\n\n")
	}

	for _, at := range schema.ActionTypes {
		if len(at.Parameters) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "export interface %sParams {\n", pascalCase(at.APIName))
		for _, p := range at.Parameters {
			tsType := resolveTSType(p.BaseType, false)
			optional := ""
			if !p.Required {
				optional = "?"
			}
			fmt.Fprintf(&buf, "  %s%s: %s;\n", p.ID, optional, tsType)
		}
		buf.WriteString("}\n\n")
	}

	return buf.Bytes(), nil
}

// linksBySource groups link types by their source ObjectType apiName.
func linksBySource(schema OntologySchema) map[string][]LinkTypeSchema {
	out := make(map[string][]LinkTypeSchema)
	for _, lt := range schema.LinkTypes {
		out[lt.SourceObjectType] = append(out[lt.SourceObjectType], lt)
	}
	return out
}

type tsClientView struct {
	Schema      OntologySchema
	ObjectTypes []tsObjectView
	ActionTypes []ActionTypeSchema
	ImportNames []string
}

type tsObjectView struct {
	APIName string
	Links   []LinkTypeSchema
}

func (g *tsGenerator) generateClient(schema OntologySchema) ([]byte, error) {
	bySource := linksBySource(schema)

	view := tsClientView{Schema: schema, ActionTypes: schema.ActionTypes}
	importSet := make(map[string]struct{})

	for _, ot := range schema.ObjectTypes {
		view.ObjectTypes = append(view.ObjectTypes, tsObjectView{
			APIName: ot.APIName,
			Links:   bySource[ot.APIName],
		})
		importSet[ot.APIName] = struct{}{}
		for _, lt := range bySource[ot.APIName] {
			importSet[lt.TargetObjectType] = struct{}{}
		}
	}
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) > 0 {
			importSet[pascalCase(at.APIName)+"Params"] = struct{}{}
		}
	}

	for name := range importSet {
		view.ImportNames = append(view.ImportNames, name)
	}
	// Stable order for deterministic output.
	for i := 0; i < len(view.ImportNames); i++ {
		for j := i + 1; j < len(view.ImportNames); j++ {
			if view.ImportNames[j] < view.ImportNames[i] {
				view.ImportNames[i], view.ImportNames[j] = view.ImportNames[j], view.ImportNames[i]
			}
		}
	}

	tmpl := template.Must(template.New("client").Funcs(template.FuncMap{
		"pascalCase": pascalCase,
		"join":       strings.Join,
	}).Parse(tsClientTmplStr))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const tsClientTmplStr = `// Auto-generated by Weave SDK Generator — do not edit.

import type { {{ join .ImportNames ", " }} } from './models';

export interface ListOptions {
  pageSize?: number;
  pageToken?: string;
}

export interface SearchOptions extends ListOptions {
  where?: Record<string, unknown>;
}

export interface ListResult<T> {
  data: T[];
  nextPageToken?: string;
}

// FetchHandler is the inner step of the middleware chain — it sends the request
// and returns the response. The terminal handler delegates to global ` + "`fetch`" + `.
export type FetchHandler = (req: Request) => Promise<Response>;

// Middleware wraps the request pipeline. Implementations receive the prepared
// Request plus the next handler in the chain; they may inspect / mutate the
// Request, short-circuit by returning a synthetic Response, or transform the
// Response on the way back. Common uses: auth header injection, structured
// logging, retry, caching, telemetry.
export type Middleware = (req: Request, next: FetchHandler) => Promise<Response>;

export class HttpClient {
  private middlewares: Middleware[] = [];

  constructor(
    public readonly baseUrl: string,
    public readonly ontology: string,
    public readonly headers: Record<string, string>,
  ) {}

  // use registers a middleware. The first middleware registered ends up at the
  // OUTERMOST layer of the chain — it sees the original request first and the
  // final response last (analogous to Express.use).
  use(mw: Middleware): void {
    this.middlewares.push(mw);
  }

  async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const req = new Request(` + "`" + `${this.baseUrl}${path}` + "`" + `, {
      method,
      headers: { ...this.headers },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    let chain: FetchHandler = (r) => fetch(r);
    for (const mw of [...this.middlewares].reverse()) {
      const next = chain;
      chain = (r) => mw(r, next);
    }
    const res = await chain(req);
    if (!res.ok) {
      throw new Error(` + "`" + `Weave API error: ${res.status} ${res.statusText}` + "`" + `);
    }
    if (res.status === 204) {
      return undefined as unknown as T;
    }
    return res.json() as Promise<T>;
  }
}
{{range .ObjectTypes}}
export class {{ .APIName }}LinkedObjects {
  constructor(private readonly http: HttpClient) {}
{{range .Links}}
  async {{ .APIName }}(pk: string): Promise<{ data: {{ .TargetObjectType }}[] }> {
    return this.http.request<{ data: {{ .TargetObjectType }}[] }>(
      'GET',
      ` + "`" + `/api/v2/ontologies/${this.http.ontology}/objects/{{ .SourceObjectType }}/${encodeURIComponent(pk)}/links/{{ .APIName }}` + "`" + `,
    );
  }
{{end}}}

export class {{ .APIName }}Repository {
  readonly linkedObjects: {{ .APIName }}LinkedObjects;

  constructor(private readonly http: HttpClient) {
    this.linkedObjects = new {{ .APIName }}LinkedObjects(http);
  }

  async get(pk: string): Promise<{{ .APIName }}> {
    return this.http.request<{{ .APIName }}>(
      'GET',
      ` + "`" + `/api/v2/ontologies/${this.http.ontology}/objects/{{ .APIName }}/${encodeURIComponent(pk)}` + "`" + `,
    );
  }

  async list(opts?: ListOptions): Promise<ListResult<{{ .APIName }}>> {
    const params = new URLSearchParams();
    if (opts?.pageSize !== undefined) params.set('pageSize', String(opts.pageSize));
    if (opts?.pageToken !== undefined) params.set('pageToken', opts.pageToken);
    const qs = params.toString();
    return this.http.request<ListResult<{{ .APIName }}>>(
      'GET',
      ` + "`" + `/api/v2/ontologies/${this.http.ontology}/objects/{{ .APIName }}${qs ? '?' + qs : ''}` + "`" + `,
    );
  }

  async search(where: Record<string, unknown>, opts?: ListOptions): Promise<ListResult<{{ .APIName }}>> {
    return this.http.request<ListResult<{{ .APIName }}>>(
      'POST',
      ` + "`" + `/api/v2/ontologies/${this.http.ontology}/objects/{{ .APIName }}/search` + "`" + `,
      { where, pageSize: opts?.pageSize, pageToken: opts?.pageToken },
    );
  }
}
{{end}}
export class WeaveClient {
  private readonly http: HttpClient;
{{range .ObjectTypes}}
  readonly {{ .APIName }}: {{ .APIName }}Repository;
{{- end}}

  constructor(baseUrl: string, ontology: string, token?: string) {
    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (token) {
      headers['Authorization'] = ` + "`" + `Bearer ${token}` + "`" + `;
    }
    this.http = new HttpClient(baseUrl, ontology, headers);
{{range .ObjectTypes}}
    this.{{ .APIName }} = new {{ .APIName }}Repository(this.http);
{{- end}}
  }

  // use installs a request interceptor / middleware. Forwards to the underlying
  // HttpClient so consumers can register cross-cutting behaviour (auth refresh,
  // logging, retry, telemetry) once on the WeaveClient.
  use(mw: Middleware): void {
    this.http.use(mw);
  }
{{range .ActionTypes}}
  async apply{{ pascalCase .APIName }}({{if .Parameters}}params: {{ pascalCase .APIName }}Params{{end}}): Promise<void> {
    await this.http.request<void>(
      'POST',
      ` + "`" + `/api/v2/ontologies/${this.http.ontology}/actions/{{ .APIName }}/apply` + "`" + `,
      {{if .Parameters}}{ parameters: params }{{else}}{}{{end}},
    );
  }
{{end}}}
`

func (g *tsGenerator) generateIndex(_ OntologySchema) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Auto-generated by Weave SDK Generator — do not edit.\n\n")
	buf.WriteString("export * from './models';\n")
	buf.WriteString("export * from './client';\n")
	return buf.Bytes()
}

func (g *tsGenerator) generatePackageJSON(schema OntologySchema) []byte {
	name := schema.Ontology.APIName
	return []byte(fmt.Sprintf(`{
  "name": "@weave/%s-sdk",
  "version": "0.1.0",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc"
  },
  "devDependencies": {
    "typescript": "^5.0.0"
  }
}
`, name))
}

func (g *tsGenerator) generateTSConfig() []byte {
	return []byte(`{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2020", "DOM"],
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src"]
}
`)
}

// resolveTSType maps a BaseType string to its TypeScript representation.
func resolveTSType(baseType string, isArray bool) string {
	mapped, ok := tsTypeMap[types.BaseType(baseType)]
	if !ok {
		mapped = "unknown"
	}
	if isArray {
		return mapped + "[]"
	}
	return mapped
}

// pascalCase converts a camelCase string to PascalCase.
func pascalCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
