package sdkgen

import (
	"bytes"
	"context"
	"fmt"
	"path"
	"strings"

	"github.com/liyang/weave/pkg/types"
)

type javaGenerator struct{}

func (g *javaGenerator) Language() string { return "java" }

// Generate emits the Java SDK in a Maven project layout:
//
//	pom.xml                                                 (root)
//	src/main/java/com/weave/<ontology>/WeaveClient.java     (single file SDK)
//	.weave-sdk.json + CHANGELOG.md                          (via appendVersionFiles)
//
// The single-file layout keeps every public type — Client, Middleware,
// RetryPolicy, TelemetryHooks, JSON helper, ListOptions/ListResult, and the
// schema-driven POJOs — in one compilation unit so the SDK package directory
// stays tidy regardless of ontology size. The SDK depends only on the Java 11+
// standard library (java.net.http.HttpClient + java.util) so `mvn compile`
// succeeds with no third-party artifacts to resolve.
func (g *javaGenerator) Generate(_ context.Context, schema OntologySchema) ([]GeneratedFile, error) {
	pkg := javaPackageSegment(schema.Ontology.APIName)
	artifact := javaArtifactID(schema.Ontology.APIName)
	pkgDir := path.Join("src/main/java/com/weave", pkg)

	var files []GeneratedFile
	files = append(files, GeneratedFile{Path: "pom.xml", Content: g.generatePom(artifact)})
	files = append(files, GeneratedFile{Path: path.Join(pkgDir, "WeaveClient.java"), Content: g.generateClient(pkg, schema)})
	files = appendVersionFiles(files, schema, g.Language())
	return files, nil
}

func (g *javaGenerator) generatePom(artifactID string) []byte {
	return []byte(fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.weave.sdk</groupId>
    <artifactId>%s</artifactId>
    <version>0.1.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
`, artifactID))
}

func (g *javaGenerator) generateClient(pkg string, schema OntologySchema) []byte {
	bySource := javaLinksBySource(schema)
	needsGeoPoint := false
	for _, ot := range schema.ObjectTypes {
		for _, p := range ot.Properties {
			if types.BaseType(p.BaseType) == types.Geopoint {
				needsGeoPoint = true
			}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package com.weave.%s;\n\n", pkg)
	buf.WriteString(`import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Function;

`)

	buf.WriteString(`/** Weave SDK client. */
public final class WeaveClient {
    private final String baseUrl;
    private final String ontology;
    private final String token;
    private final HttpClient http;
    private final List<Middleware> middlewares = new ArrayList<>();

    public WeaveClient(String baseUrl, String ontology, String token) {
        this(baseUrl, ontology, token, HttpClient.newHttpClient());
    }

    public WeaveClient(String baseUrl, String ontology, String token, HttpClient http) {
        this.baseUrl = baseUrl;
        this.ontology = ontology;
        this.token = token;
        this.http = http;
    }

    public String getBaseUrl() { return baseUrl; }
    public String getOntology() { return ontology; }

    /** Register a middleware. The first middleware registered ends up at the OUTERMOST layer. */
    public WeaveClient use(Middleware mw) {
        middlewares.add(mw);
        return this;
    }

    public WeaveClient useRetry(RetryPolicy policy) {
        return use(retryMiddleware(policy));
    }

    public WeaveClient useTelemetry(TelemetryHooks hooks) {
        return use(telemetryMiddleware(hooks));
    }

    /** Inner pipeline step: execute the prepared HTTP request. */
    @FunctionalInterface
    public interface RoundTripFunc {
        HttpResponse<byte[]> handle(HttpRequest req) throws IOException, InterruptedException;
    }

    /** Wraps the request pipeline. May inspect/mutate the request, short-circuit, or transform the response. */
    @FunctionalInterface
    public interface Middleware {
        HttpResponse<byte[]> handle(HttpRequest req, RoundTripFunc next) throws IOException, InterruptedException;
    }

    /** Three-argument consumer for telemetry hook ergonomics. */
    @FunctionalInterface
    public interface TriConsumer<A, B, C> {
        void accept(A a, B b, C c);
    }

    /** OpenTelemetry-style instrumentation hooks. */
    public static final class TelemetryHooks {
        public Function<HttpRequest, Object> onRequest;
        public TriConsumer<HttpRequest, HttpResponse<byte[]>, Object> onResponse;
        public TriConsumer<HttpRequest, Throwable, Object> onError;
    }

    public static Middleware telemetryMiddleware(final TelemetryHooks hooks) {
        return (req, next) -> {
            Object span = null;
            if (hooks != null && hooks.onRequest != null) {
                span = hooks.onRequest.apply(req);
            }
            HttpResponse<byte[]> resp;
            try {
                resp = next.handle(req);
            } catch (IOException | InterruptedException | RuntimeException e) {
                if (hooks != null && hooks.onError != null) {
                    hooks.onError.accept(req, e, span);
                }
                throw e;
            }
            if (hooks != null && hooks.onResponse != null) {
                hooks.onResponse.accept(req, resp, span);
            }
            return resp;
        };
    }

    /**
     * Configures the built-in retry middleware. Idempotent methods only
     * (GET / HEAD / OPTIONS / PUT / DELETE) on retriable status codes
     * (408, 425, 429, 500, 502, 503, 504). Backoff is exponential with full
     * jitter; an explicit Retry-After header overrides the computed delay.
     */
    public static final class RetryPolicy {
        public int maxAttempts = 3;
        public Duration baseDelay = Duration.ofMillis(100);
        public Duration maxDelay = Duration.ofSeconds(5);
        public double multiplier = 2.0;
        public Set<Integer> retryStatuses = new HashSet<>(Arrays.asList(408, 425, 429, 500, 502, 503, 504));
        public Set<String> retryMethods = new HashSet<>(Arrays.asList("GET", "HEAD", "OPTIONS", "PUT", "DELETE"));
        public Random rand;
    }

    public static Middleware retryMiddleware(final RetryPolicy policy) {
        final int maxAttempts = policy.maxAttempts <= 0 ? 3 : policy.maxAttempts;
        final long baseMs = policy.baseDelay == null || policy.baseDelay.isZero() || policy.baseDelay.isNegative()
                ? 100L : policy.baseDelay.toMillis();
        final long maxMs = policy.maxDelay == null || policy.maxDelay.toMillis() < baseMs
                ? 5000L : policy.maxDelay.toMillis();
        final double mult = policy.multiplier <= 0 ? 2.0 : policy.multiplier;
        final Set<Integer> statuses = policy.retryStatuses == null || policy.retryStatuses.isEmpty()
                ? new HashSet<>(Arrays.asList(408, 425, 429, 500, 502, 503, 504))
                : policy.retryStatuses;
        final Set<String> methods = policy.retryMethods == null || policy.retryMethods.isEmpty()
                ? new HashSet<>(Arrays.asList("GET", "HEAD", "OPTIONS", "PUT", "DELETE"))
                : policy.retryMethods;

        return (req, next) -> {
            if (!methods.contains(req.method().toUpperCase())) {
                return next.handle(req);
            }
            HttpResponse<byte[]> last = null;
            Throwable lastErr = null;
            for (int attempt = 0; attempt < maxAttempts; attempt++) {
                try {
                    HttpResponse<byte[]> resp = next.handle(req);
                    if (!statuses.contains(resp.statusCode()) || attempt == maxAttempts - 1) {
                        return resp;
                    }
                    last = resp;
                    lastErr = null;
                } catch (IOException | RuntimeException e) {
                    if (attempt == maxAttempts - 1) {
                        throw e;
                    }
                    lastErr = e;
                    last = null;
                }
                long capMs = (long) Math.min((double) maxMs, (double) baseMs * Math.pow(mult, attempt));
                long delay = jitter(policy.rand, capMs);
                if (last != null) {
                    Long retryAfter = parseRetryAfter(last.headers().firstValue("Retry-After").orElse(""));
                    if (retryAfter != null) {
                        delay = Math.min(retryAfter, maxMs);
                    }
                }
                if (delay > 0) {
                    try { Thread.sleep(delay); } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt();
                        throw ie;
                    }
                }
            }
            if (lastErr instanceof IOException) throw (IOException) lastErr;
            if (lastErr instanceof RuntimeException) throw (RuntimeException) lastErr;
            throw new RuntimeException("retry middleware: exhausted attempts");
        };
    }

    private static long jitter(Random rand, long capMs) {
        if (capMs <= 0) return 0;
        if (rand != null) return (long) (rand.nextDouble() * (capMs + 1));
        return ThreadLocalRandom.current().nextLong(capMs + 1);
    }

    private static Long parseRetryAfter(String header) {
        if (header == null || header.isEmpty()) return null;
        try {
            long secs = Long.parseLong(header.trim());
            if (secs < 0) return 0L;
            return secs * 1000L;
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    /** Pagination options for list/search endpoints. */
    public static final class ListOptions {
        public int pageSize;
        public String pageToken;
    }

    /** Paginated response envelope. */
    public static final class ListResult<T> {
        public List<T> data;
        public String nextPageToken;
    }
`)

	if needsGeoPoint {
		buf.WriteString(`
    /** Geographic coordinate. */
    public static final class GeoPoint {
        public Double lat;
        public Double lon;
    }
`)
	}

	// Per-ObjectType POJOs as nested static classes
	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "\n    /** %s POJO. */\n", ot.APIName)
		fmt.Fprintf(&buf, "    public static final class %s {\n", ot.APIName)
		for _, p := range ot.Properties {
			javaType := resolveJavaType(p.BaseType, p.IsArray)
			fmt.Fprintf(&buf, "        public %s %s;\n", javaType, javaSafeFieldName(p.APIName))
		}
		buf.WriteString("\n        @SuppressWarnings(\"unchecked\")\n")
		fmt.Fprintf(&buf, "        public static %s fromMap(Map<String, Object> m) {\n", ot.APIName)
		buf.WriteString("            if (m == null) return null;\n")
		fmt.Fprintf(&buf, "            %s out = new %s();\n", ot.APIName, ot.APIName)
		for _, p := range ot.Properties {
			fname := javaSafeFieldName(p.APIName)
			fmt.Fprintf(&buf, "            out.%s = %s;\n", fname, javaCoerceExpr(fmt.Sprintf("m.get(%q)", p.APIName), p.BaseType, p.IsArray))
		}
		buf.WriteString("            return out;\n")
		buf.WriteString("        }\n")
		buf.WriteString("    }\n")
	}

	// Per-Action params POJOs
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\n    /** Parameters for the %s action. */\n", at.APIName)
		fmt.Fprintf(&buf, "    public static final class %sParams {\n", pascalCase(at.APIName))
		for _, p := range at.Parameters {
			javaType := resolveJavaType(p.BaseType, false)
			fmt.Fprintf(&buf, "        public %s %s;\n", javaType, javaSafeFieldName(p.ID))
		}
		buf.WriteString("\n        Map<String, Object> toMap() {\n")
		buf.WriteString("            Map<String, Object> m = new LinkedHashMap<>();\n")
		for _, p := range at.Parameters {
			fname := javaSafeFieldName(p.ID)
			fmt.Fprintf(&buf, "            if (this.%s != null) m.put(%q, this.%s);\n", fname, p.ID, fname)
		}
		buf.WriteString("            return m;\n")
		buf.WriteString("        }\n")
		buf.WriteString("    }\n")
	}

	// Per-ObjectType API methods
	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "\n    public %s get%s(String pk) throws IOException, InterruptedException {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "        String url = baseUrl + \"/api/v2/ontologies/\" + enc(ontology) + \"/objects/%s/\" + enc(pk);\n", ot.APIName)
		buf.WriteString("        Object body = decodeJson(doRequest(\"GET\", url, null));\n")
		fmt.Fprintf(&buf, "        return %s.fromMap(asMap(body));\n", ot.APIName)
		buf.WriteString("    }\n")

		fmt.Fprintf(&buf, "\n    public ListResult<%s> list%s(ListOptions opts) throws IOException, InterruptedException {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "        String url = baseUrl + \"/api/v2/ontologies/\" + enc(ontology) + \"/objects/%s\" + listQuery(opts);\n", ot.APIName)
		fmt.Fprintf(&buf, "        return decodeListResult(doRequest(\"GET\", url, null), %s::fromMap);\n", ot.APIName)
		buf.WriteString("    }\n")

		fmt.Fprintf(&buf, "\n    public ListResult<%s> search%s(Map<String, Object> where, ListOptions opts) throws IOException, InterruptedException {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "        String url = baseUrl + \"/api/v2/ontologies/\" + enc(ontology) + \"/objects/%s/search\";\n", ot.APIName)
		buf.WriteString("        Map<String, Object> body = new LinkedHashMap<>();\n")
		buf.WriteString("        body.put(\"where\", where);\n")
		buf.WriteString("        if (opts != null && opts.pageSize > 0) body.put(\"pageSize\", opts.pageSize);\n")
		buf.WriteString("        if (opts != null && opts.pageToken != null && !opts.pageToken.isEmpty()) body.put(\"pageToken\", opts.pageToken);\n")
		fmt.Fprintf(&buf, "        return decodeListResult(doRequest(\"POST\", url, body), %s::fromMap);\n", ot.APIName)
		buf.WriteString("    }\n")

		for _, lt := range bySource[ot.APIName] {
			method := fmt.Sprintf("linkedObjects%s%s", ot.APIName, pascalCase(lt.APIName))
			fmt.Fprintf(&buf, "\n    @SuppressWarnings(\"unchecked\")\n")
			fmt.Fprintf(&buf, "    public List<%s> %s(String pk) throws IOException, InterruptedException {\n", lt.TargetObjectType, method)
			fmt.Fprintf(&buf, "        String url = baseUrl + \"/api/v2/ontologies/\" + enc(ontology) + \"/objects/%s/\" + enc(pk) + \"/links/%s\";\n",
				lt.SourceObjectType, lt.APIName)
			buf.WriteString("        Map<String, Object> body = asMap(decodeJson(doRequest(\"GET\", url, null)));\n")
			buf.WriteString("        Object data = body == null ? null : body.get(\"data\");\n")
			fmt.Fprintf(&buf, "        List<%s> out = new ArrayList<>();\n", lt.TargetObjectType)
			buf.WriteString("        if (data instanceof List) {\n")
			buf.WriteString("            for (Object item : (List<Object>) data) {\n")
			fmt.Fprintf(&buf, "                out.add(%s.fromMap(asMap(item)));\n", lt.TargetObjectType)
			buf.WriteString("            }\n")
			buf.WriteString("        }\n")
			buf.WriteString("        return out;\n")
			buf.WriteString("    }\n")
		}
	}

	// Action Apply methods
	for _, at := range schema.ActionTypes {
		method := "apply" + pascalCase(at.APIName)
		fmt.Fprintf(&buf, "\n    public void %s(", method)
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "%sParams params", pascalCase(at.APIName))
		}
		buf.WriteString(") throws IOException, InterruptedException {\n")
		fmt.Fprintf(&buf, "        String url = baseUrl + \"/api/v2/ontologies/\" + enc(ontology) + \"/actions/%s/apply\";\n", at.APIName)
		if len(at.Parameters) > 0 {
			buf.WriteString("        Map<String, Object> body = new LinkedHashMap<>();\n")
			buf.WriteString("        body.put(\"parameters\", params == null ? new LinkedHashMap<>() : params.toMap());\n")
			buf.WriteString("        doRequest(\"POST\", url, body);\n")
		} else {
			buf.WriteString("        doRequest(\"POST\", url, null);\n")
		}
		buf.WriteString("    }\n")
	}

	// Function execute methods
	buf.WriteString(`
    /**
     * Generic Function execution helper. Posts the wire envelope
     * { "parameters": ... } to /api/v2/ontologies/{ontology}/functions/{ref}/execute
     * and returns the decoded response body as a Map.
     */
    public Map<String, Object> executeFunction(String ref, Map<String, Object> params) throws IOException, InterruptedException {
        String url = baseUrl + "/api/v2/ontologies/" + enc(ontology) + "/functions/" + enc(ref) + "/execute";
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("parameters", params == null ? new LinkedHashMap<>() : params);
        return asMap(decodeJson(doRequest("POST", url, body)));
    }
`)

	for _, fn := range schema.Functions {
		ref := fn.Name
		if fn.Version != "" {
			ref = fn.Name + "@" + fn.Version
		}
		method := "execute" + pascalCase(javaSafeIdent(fn.Name))
		fmt.Fprintf(&buf, "\n    /** Executes the %s Function (ref=%q). */\n", fn.Name, ref)
		fmt.Fprintf(&buf, "    public Map<String, Object> %s(Map<String, Object> params) throws IOException, InterruptedException {\n", method)
		fmt.Fprintf(&buf, "        return executeFunction(%q, params);\n", ref)
		buf.WriteString("    }\n")
	}

	// Core HTTP / helpers
	buf.WriteString(`
    private byte[] doRequest(String method, String url, Object body) throws IOException, InterruptedException {
        HttpRequest.Builder rb = HttpRequest.newBuilder(URI.create(url));
        rb.header("Content-Type", "application/json");
        if (token != null && !token.isEmpty()) {
            rb.header("Authorization", "Bearer " + token);
        }
        HttpRequest.BodyPublisher publisher = body == null
                ? HttpRequest.BodyPublishers.noBody()
                : HttpRequest.BodyPublishers.ofString(encodeJson(body), StandardCharsets.UTF_8);
        rb.method(method, publisher);
        HttpRequest req = rb.build();
        RoundTripFunc next = r -> http.send(r, HttpResponse.BodyHandlers.ofByteArray());
        for (int i = middlewares.size() - 1; i >= 0; i--) {
            final Middleware mw = middlewares.get(i);
            final RoundTripFunc prev = next;
            next = r -> mw.handle(r, prev);
        }
        HttpResponse<byte[]> resp = next.handle(req);
        if (resp.statusCode() >= 400) {
            throw new IOException("weave API error: " + resp.statusCode());
        }
        return resp.body();
    }

    private static String enc(String s) {
        return URLEncoder.encode(s == null ? "" : s, StandardCharsets.UTF_8).replace("+", "%20");
    }

    private static String listQuery(ListOptions opts) {
        if (opts == null) return "";
        StringBuilder sb = new StringBuilder();
        if (opts.pageSize > 0) sb.append("pageSize=").append(opts.pageSize);
        if (opts.pageToken != null && !opts.pageToken.isEmpty()) {
            if (sb.length() > 0) sb.append('&');
            sb.append("pageToken=").append(enc(opts.pageToken));
        }
        return sb.length() == 0 ? "" : "?" + sb;
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> asMap(Object o) {
        if (o instanceof Map) return (Map<String, Object>) o;
        return null;
    }

    @SuppressWarnings("unchecked")
    private static <T> ListResult<T> decodeListResult(byte[] raw, Function<Map<String, Object>, T> conv) {
        ListResult<T> out = new ListResult<>();
        out.data = new ArrayList<>();
        Object decoded = decodeJson(raw);
        Map<String, Object> envelope = asMap(decoded);
        if (envelope == null) return out;
        Object data = envelope.get("data");
        if (data instanceof List) {
            for (Object item : (List<Object>) data) {
                out.data.add(conv.apply(asMap(item)));
            }
        }
        Object next = envelope.get("nextPageToken");
        if (next instanceof String) out.nextPageToken = (String) next;
        return out;
    }

    private static Object decodeJson(byte[] raw) {
        if (raw == null || raw.length == 0) return null;
        return Json.decode(new String(raw, StandardCharsets.UTF_8));
    }

    private static String encodeJson(Object value) {
        return Json.encode(value);
    }

    // -- type coercion helpers used by generated POJO fromMap factories --

    static Integer asInt(Object o) {
        if (o == null) return null;
        if (o instanceof Number) return ((Number) o).intValue();
        if (o instanceof String) try { return Integer.parseInt((String) o); } catch (NumberFormatException e) { return null; }
        return null;
    }
    static Long asLong(Object o) {
        if (o == null) return null;
        if (o instanceof Number) return ((Number) o).longValue();
        if (o instanceof String) try { return Long.parseLong((String) o); } catch (NumberFormatException e) { return null; }
        return null;
    }
    static Short asShort(Object o) {
        Integer i = asInt(o);
        return i == null ? null : i.shortValue();
    }
    static Byte asByte(Object o) {
        Integer i = asInt(o);
        return i == null ? null : i.byteValue();
    }
    static Double asDouble(Object o) {
        if (o == null) return null;
        if (o instanceof Number) return ((Number) o).doubleValue();
        if (o instanceof String) try { return Double.parseDouble((String) o); } catch (NumberFormatException e) { return null; }
        return null;
    }
    static Float asFloat(Object o) {
        Double d = asDouble(o);
        return d == null ? null : d.floatValue();
    }
    static Boolean asBoolean(Object o) {
        if (o instanceof Boolean) return (Boolean) o;
        return null;
    }
    static String asString(Object o) {
        return o == null ? null : o.toString();
    }
`)

	if needsGeoPoint {
		buf.WriteString(`
    @SuppressWarnings("unchecked")
    static GeoPoint asGeoPoint(Object o) {
        Map<String, Object> m = asMap(o);
        if (m == null) return null;
        GeoPoint p = new GeoPoint();
        p.lat = asDouble(m.get("lat"));
        p.lon = asDouble(m.get("lon"));
        return p;
    }
`)
	}

	buf.WriteString(`
    @SuppressWarnings("unchecked")
    static <T> List<T> asList(Object o, Function<Object, T> conv) {
        if (!(o instanceof List)) return null;
        List<Object> raw = (List<Object>) o;
        List<T> out = new ArrayList<>(raw.size());
        for (Object item : raw) out.add(conv.apply(item));
        return out;
    }

    /**
     * Minimal JSON encoder/decoder. Encodes Map / Collection / String /
     * Number / Boolean / null. Decoded numbers become Long if integer,
     * Double if fractional. Decoded objects are LinkedHashMap, decoded
     * arrays are ArrayList.
     */
    public static final class Json {
        private Json() {}

        public static String encode(Object value) {
            StringBuilder sb = new StringBuilder();
            encodeInto(sb, value);
            return sb.toString();
        }

        public static Object decode(String src) {
            Decoder d = new Decoder(src);
            d.skipWs();
            Object v = d.parseValue();
            d.skipWs();
            if (d.pos < src.length()) {
                throw new IllegalArgumentException("Json.decode: trailing data at " + d.pos);
            }
            return v;
        }

        private static void encodeInto(StringBuilder sb, Object value) {
            if (value == null) { sb.append("null"); return; }
            if (value instanceof Boolean || value instanceof Number) { sb.append(value); return; }
            if (value instanceof String) { encodeString(sb, (String) value); return; }
            if (value instanceof Map) {
                sb.append('{');
                boolean first = true;
                for (Map.Entry<?, ?> e : ((Map<?, ?>) value).entrySet()) {
                    if (!first) sb.append(',');
                    first = false;
                    encodeString(sb, e.getKey() == null ? "null" : e.getKey().toString());
                    sb.append(':');
                    encodeInto(sb, e.getValue());
                }
                sb.append('}');
                return;
            }
            if (value instanceof Collection) {
                sb.append('[');
                boolean first = true;
                for (Object item : (Collection<?>) value) {
                    if (!first) sb.append(',');
                    first = false;
                    encodeInto(sb, item);
                }
                sb.append(']');
                return;
            }
            // Fallback: stringify unsupported types so encoding never throws.
            encodeString(sb, value.toString());
        }

        private static void encodeString(StringBuilder sb, String s) {
            sb.append('"');
            for (int i = 0; i < s.length(); i++) {
                char c = s.charAt(i);
                switch (c) {
                    case '"': sb.append("\\\""); break;
                    case '\\': sb.append("\\\\"); break;
                    case '\n': sb.append("\\n"); break;
                    case '\r': sb.append("\\r"); break;
                    case '\t': sb.append("\\t"); break;
                    case '\b': sb.append("\\b"); break;
                    case '\f': sb.append("\\f"); break;
                    default:
                        if (c < 0x20) {
                            sb.append(String.format("\\u%04x", (int) c));
                        } else {
                            sb.append(c);
                        }
                }
            }
            sb.append('"');
        }

        private static final class Decoder {
            final String s; int pos;
            Decoder(String s) { this.s = s; this.pos = 0; }

            void skipWs() {
                while (pos < s.length() && Character.isWhitespace(s.charAt(pos))) pos++;
            }

            Object parseValue() {
                skipWs();
                if (pos >= s.length()) throw new IllegalArgumentException("Json: unexpected EOF");
                char c = s.charAt(pos);
                switch (c) {
                    case '{': return parseObject();
                    case '[': return parseArray();
                    case '"': return parseString();
                    case 't': case 'f': return parseBool();
                    case 'n': return parseNull();
                    default: return parseNumber();
                }
            }

            Map<String, Object> parseObject() {
                pos++;
                Map<String, Object> m = new LinkedHashMap<>();
                skipWs();
                if (pos < s.length() && s.charAt(pos) == '}') { pos++; return m; }
                while (true) {
                    skipWs();
                    String k = parseString();
                    skipWs();
                    if (pos >= s.length() || s.charAt(pos) != ':') {
                        throw new IllegalArgumentException("Json: expected ':' at " + pos);
                    }
                    pos++;
                    Object v = parseValue();
                    m.put(k, v);
                    skipWs();
                    if (pos >= s.length()) throw new IllegalArgumentException("Json: unexpected EOF in object");
                    char c = s.charAt(pos);
                    if (c == ',') { pos++; continue; }
                    if (c == '}') { pos++; return m; }
                    throw new IllegalArgumentException("Json: unexpected char in object at " + pos + ": " + c);
                }
            }

            List<Object> parseArray() {
                pos++;
                List<Object> out = new ArrayList<>();
                skipWs();
                if (pos < s.length() && s.charAt(pos) == ']') { pos++; return out; }
                while (true) {
                    Object v = parseValue();
                    out.add(v);
                    skipWs();
                    if (pos >= s.length()) throw new IllegalArgumentException("Json: unexpected EOF in array");
                    char c = s.charAt(pos);
                    if (c == ',') { pos++; continue; }
                    if (c == ']') { pos++; return out; }
                    throw new IllegalArgumentException("Json: unexpected char in array at " + pos + ": " + c);
                }
            }

            String parseString() {
                if (pos >= s.length() || s.charAt(pos) != '"') {
                    throw new IllegalArgumentException("Json: expected string at " + pos);
                }
                pos++;
                StringBuilder sb = new StringBuilder();
                while (pos < s.length()) {
                    char c = s.charAt(pos++);
                    if (c == '"') return sb.toString();
                    if (c == '\\') {
                        if (pos >= s.length()) throw new IllegalArgumentException("Json: bad escape");
                        char esc = s.charAt(pos++);
                        switch (esc) {
                            case '"': sb.append('"'); break;
                            case '\\': sb.append('\\'); break;
                            case '/': sb.append('/'); break;
                            case 'n': sb.append('\n'); break;
                            case 'r': sb.append('\r'); break;
                            case 't': sb.append('\t'); break;
                            case 'b': sb.append('\b'); break;
                            case 'f': sb.append('\f'); break;
                            case 'u':
                                if (pos + 4 > s.length()) throw new IllegalArgumentException("Json: bad unicode");
                                sb.append((char) Integer.parseInt(s.substring(pos, pos + 4), 16));
                                pos += 4;
                                break;
                            default: throw new IllegalArgumentException("Json: bad escape \\" + esc);
                        }
                    } else {
                        sb.append(c);
                    }
                }
                throw new IllegalArgumentException("Json: unterminated string");
            }

            Boolean parseBool() {
                if (s.startsWith("true", pos)) { pos += 4; return Boolean.TRUE; }
                if (s.startsWith("false", pos)) { pos += 5; return Boolean.FALSE; }
                throw new IllegalArgumentException("Json: bad bool at " + pos);
            }

            Object parseNull() {
                if (s.startsWith("null", pos)) { pos += 4; return null; }
                throw new IllegalArgumentException("Json: bad null at " + pos);
            }

            Number parseNumber() {
                int start = pos;
                if (pos < s.length() && s.charAt(pos) == '-') pos++;
                while (pos < s.length() && Character.isDigit(s.charAt(pos))) pos++;
                boolean isFloat = false;
                if (pos < s.length() && s.charAt(pos) == '.') {
                    isFloat = true;
                    pos++;
                    while (pos < s.length() && Character.isDigit(s.charAt(pos))) pos++;
                }
                if (pos < s.length() && (s.charAt(pos) == 'e' || s.charAt(pos) == 'E')) {
                    isFloat = true;
                    pos++;
                    if (pos < s.length() && (s.charAt(pos) == '+' || s.charAt(pos) == '-')) pos++;
                    while (pos < s.length() && Character.isDigit(s.charAt(pos))) pos++;
                }
                String num = s.substring(start, pos);
                if (isFloat) return Double.parseDouble(num);
                return Long.parseLong(num);
            }
        }
    }
}
`)

	return buf.Bytes()
}

func resolveJavaType(baseType string, isArray bool) string {
	mapped, ok := javaTypeMap[types.BaseType(baseType)]
	if !ok {
		mapped = "Object"
	}
	if isArray {
		return "List<" + mapped + ">"
	}
	return mapped
}

// javaCoerceExpr returns a Java expression that coerces an Object reference
// (typically the result of `m.get("propertyName")`) into the strongly-typed
// field. Generated code lives inside WeaveClient so the static helpers are
// directly callable without a class qualifier.
func javaCoerceExpr(getExpr, baseType string, isArray bool) string {
	if isArray {
		inner := javaScalarCoerce("o", baseType)
		return fmt.Sprintf("asList(%s, o -> %s)", getExpr, inner)
	}
	return javaScalarCoerce(getExpr, baseType)
}

func javaScalarCoerce(value, baseType string) string {
	switch types.BaseType(baseType) {
	case types.String, types.Date, types.Timestamp, types.Decimal,
		types.Attachment, types.TimeSeries, types.MediaReference,
		types.Media, types.Marking, types.Cipher:
		return fmt.Sprintf("asString(%s)", value)
	case types.Integer:
		return fmt.Sprintf("asInt(%s)", value)
	case types.Short:
		return fmt.Sprintf("asShort(%s)", value)
	case types.Long:
		return fmt.Sprintf("asLong(%s)", value)
	case types.Byte:
		return fmt.Sprintf("asByte(%s)", value)
	case types.Float:
		return fmt.Sprintf("asFloat(%s)", value)
	case types.Double:
		return fmt.Sprintf("asDouble(%s)", value)
	case types.Boolean:
		return fmt.Sprintf("asBoolean(%s)", value)
	case types.Geopoint:
		return fmt.Sprintf("asGeoPoint(%s)", value)
	default:
		return value
	}
}

func javaLinksBySource(schema OntologySchema) map[string][]LinkTypeSchema {
	out := make(map[string][]LinkTypeSchema)
	for _, lt := range schema.LinkTypes {
		out[lt.SourceObjectType] = append(out[lt.SourceObjectType], lt)
	}
	return out
}

// javaPackageSegment sanitises an ontology API name into a single Java
// package segment — lowercase letters / digits / underscores, leading digit
// prefixed with `_`. Empty input falls back to `weavesdk` so a degenerate
// schema still emits a valid package declaration.
func javaPackageSegment(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_':
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "weavesdk"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	if isJavaReservedWord(out) {
		out = out + "_"
	}
	return out
}

// javaArtifactID derives a Maven-friendly artifactId — lowercase, digits,
// hyphens. Empty input → `weave-sdk`.
func javaArtifactID(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "weave-sdk"
	}
	return "weave-" + out + "-sdk"
}

// javaSafeFieldName returns the API name unchanged unless it collides with a
// Java reserved word, in which case a trailing underscore is appended.
func javaSafeFieldName(name string) string {
	if isJavaReservedWord(name) {
		return name + "_"
	}
	return name
}

// javaSafeIdent sanitises an arbitrary identifier (Function names may contain
// dots, hyphens, slashes) so it can flow into pascalCase to produce a valid
// Java method name. Non-alphanumeric runes collapse the case-bump cursor;
// runs of letters/digits round-trip unchanged.
func javaSafeIdent(s string) string {
	var b strings.Builder
	upperNext := false
	for i, r := range s {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'):
			if upperNext {
				if r >= 'a' && r <= 'z' {
					r = r - ('a' - 'A')
				}
				upperNext = false
			}
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteRune('_')
			}
			b.WriteRune(r)
		default:
			upperNext = true
		}
	}
	out := b.String()
	if out == "" {
		return "Function"
	}
	return out
}

func isJavaReservedWord(s string) bool {
	_, ok := javaReservedWords[s]
	return ok
}

var javaReservedWords = map[string]struct{}{
	"abstract": {}, "assert": {}, "boolean": {}, "break": {}, "byte": {},
	"case": {}, "catch": {}, "char": {}, "class": {}, "const": {},
	"continue": {}, "default": {}, "do": {}, "double": {}, "else": {},
	"enum": {}, "extends": {}, "final": {}, "finally": {}, "float": {},
	"for": {}, "goto": {}, "if": {}, "implements": {}, "import": {},
	"instanceof": {}, "int": {}, "interface": {}, "long": {}, "native": {},
	"new": {}, "package": {}, "private": {}, "protected": {}, "public": {},
	"return": {}, "short": {}, "static": {}, "strictfp": {}, "super": {},
	"switch": {}, "synchronized": {}, "this": {}, "throw": {}, "throws": {},
	"transient": {}, "try": {}, "void": {}, "volatile": {}, "while": {},
	"true": {}, "false": {}, "null": {},
}
