package sdkgen

import (
	"bytes"
	"context"
	"fmt"

	"github.com/liyang/weave/pkg/types"
)

type pythonGenerator struct{}

func (g *pythonGenerator) Language() string { return "python" }

func (g *pythonGenerator) Generate(_ context.Context, schema OntologySchema) ([]GeneratedFile, error) {
	var files []GeneratedFile

	// models.py — Pydantic BaseModel per ObjectType
	models, err := g.generateModels(schema)
	if err != nil {
		return nil, fmt.Errorf("generate models: %w", err)
	}
	files = append(files, GeneratedFile{Path: "weave_sdk/models.py", Content: models})

	// client.py
	client, err := g.generateClient(schema)
	if err != nil {
		return nil, fmt.Errorf("generate client: %w", err)
	}
	files = append(files, GeneratedFile{Path: "weave_sdk/client.py", Content: client})

	// __init__.py
	init := g.generateInit(schema)
	files = append(files, GeneratedFile{Path: "weave_sdk/__init__.py", Content: init})

	// pyproject.toml
	proj := g.generatePyproject(schema)
	files = append(files, GeneratedFile{Path: "pyproject.toml", Content: proj})

	// py.typed — PEP 561 marker so downstream mypy picks up inline type hints
	files = append(files, GeneratedFile{Path: "weave_sdk/py.typed", Content: []byte("# PEP 561 marker\n")})

	return files, nil
}

func (g *pythonGenerator) generateModels(schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by Weave SDK Generator — do not edit.\n\n")
	buf.WriteString("from __future__ import annotations\n\n")
	buf.WriteString("import datetime\nfrom decimal import Decimal\nfrom typing import Any, Optional\n\n")
	buf.WriteString("from pydantic import BaseModel\n\n")

	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "\nclass %s(BaseModel):\n", ot.APIName)
		if len(ot.Properties) == 0 {
			buf.WriteString("    pass\n")
			continue
		}
		for _, p := range ot.Properties {
			pyType := resolvePythonType(p.BaseType, p.IsArray)
			fmt.Fprintf(&buf, "    %s: %s\n", p.APIName, pyType)
		}
	}
	buf.WriteString("\n")

	// Action parameter models
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\nclass %sParams(BaseModel):\n", pascalCase(at.APIName))
		for _, p := range at.Parameters {
			pyType := resolvePythonType(p.BaseType, false)
			if !p.Required {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}
			fmt.Fprintf(&buf, "    %s: %s\n", p.ID, pyType)
		}
	}

	return buf.Bytes(), nil
}

func (g *pythonGenerator) generateClient(schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by Weave SDK Generator — do not edit.\n\n")
	buf.WriteString("from __future__ import annotations\n\n")
	buf.WriteString("from typing import Any, Optional\n\n")
	buf.WriteString("import httpx\n\n")

	// Import models
	buf.WriteString("from .models import (\n")
	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "    %s,\n", ot.APIName)
	}
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "    %sParams,\n", pascalCase(at.APIName))
		}
	}
	buf.WriteString(")\n\n\n")

	buf.WriteString("class WeaveClient:\n")
	buf.WriteString("    def __init__(self, base_url: str, ontology: str, token: Optional[str] = None) -> None:\n")
	buf.WriteString("        self.base_url = base_url\n")
	buf.WriteString("        self.ontology = ontology\n")
	buf.WriteString("        headers: dict[str, str] = {}\n")
	buf.WriteString("        if token:\n")
	buf.WriteString("            headers[\"Authorization\"] = f\"Bearer {token}\"\n")
	buf.WriteString("        self._client = httpx.Client(base_url=base_url, headers=headers)\n\n")

	for _, ot := range schema.ObjectTypes {
		lower := snakeCase(ot.APIName)
		fmt.Fprintf(&buf, "    def get_%s(self, pk: str) -> %s:\n", lower, ot.APIName)
		fmt.Fprintf(&buf, "        r = self._client.get(f\"/api/v2/ontologies/{self.ontology}/objects/%s/{pk}\")\n", ot.APIName)
		buf.WriteString("        r.raise_for_status()\n")
		fmt.Fprintf(&buf, "        return %s(**r.json())\n\n", ot.APIName)

		fmt.Fprintf(&buf, "    def list_%s(self, page_size: int = 100, page_token: Optional[str] = None) -> dict[str, Any]:\n", lower)
		buf.WriteString("        params: dict[str, Any] = {\"pageSize\": page_size}\n")
		buf.WriteString("        if page_token:\n")
		buf.WriteString("            params[\"pageToken\"] = page_token\n")
		fmt.Fprintf(&buf, "        r = self._client.get(f\"/api/v2/ontologies/{self.ontology}/objects/%s\", params=params)\n", ot.APIName)
		buf.WriteString("        r.raise_for_status()\n")
		buf.WriteString("        return r.json()\n\n")

		fmt.Fprintf(&buf, "    def search_%s(self, where: dict[str, Any], page_size: int = 100) -> dict[str, Any]:\n", lower)
		fmt.Fprintf(&buf, "        r = self._client.post(f\"/api/v2/ontologies/{self.ontology}/objects/%s/search\", json={\"where\": where, \"pageSize\": page_size})\n", ot.APIName)
		buf.WriteString("        r.raise_for_status()\n")
		buf.WriteString("        return r.json()\n\n")
	}

	for _, at := range schema.ActionTypes {
		lower := snakeCase(at.APIName)
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "    def apply_%s(self, params: %sParams) -> None:\n", lower, pascalCase(at.APIName))
			fmt.Fprintf(&buf, "        r = self._client.post(f\"/api/v2/ontologies/{self.ontology}/actions/%s/apply\", json={\"parameters\": params.model_dump()})\n", at.APIName)
		} else {
			fmt.Fprintf(&buf, "    def apply_%s(self) -> None:\n", lower)
			fmt.Fprintf(&buf, "        r = self._client.post(f\"/api/v2/ontologies/{self.ontology}/actions/%s/apply\")\n", at.APIName)
		}
		buf.WriteString("        r.raise_for_status()\n\n")
	}

	return buf.Bytes(), nil
}

func (g *pythonGenerator) generateInit(schema OntologySchema) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by Weave SDK Generator — do not edit.\n\n")
	buf.WriteString("from .client import WeaveClient\n")
	buf.WriteString("from .models import (\n")
	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "    %s,\n", ot.APIName)
	}
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "    %sParams,\n", pascalCase(at.APIName))
		}
	}
	buf.WriteString(")\n\n")
	buf.WriteString("__all__ = [\n")
	buf.WriteString("    \"WeaveClient\",\n")
	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "    \"%s\",\n", ot.APIName)
	}
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "    \"%sParams\",\n", pascalCase(at.APIName))
		}
	}
	buf.WriteString("]\n")
	return buf.Bytes()
}

func (g *pythonGenerator) generatePyproject(schema OntologySchema) []byte {
	name := schema.Ontology.APIName
	return []byte(fmt.Sprintf(`[project]
name = "weave-%s-sdk"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.25.0",
    "pydantic>=2.0.0",
]
`, name))
}

func resolvePythonType(baseType string, isArray bool) string {
	mapped, ok := pythonTypeMap[types.BaseType(baseType)]
	if !ok {
		mapped = "Any"
	}
	if isArray {
		return fmt.Sprintf("list[%s]", mapped)
	}
	return mapped
}

// snakeCase converts camelCase to snake_case.
func snakeCase(s string) string {
	var result bytes.Buffer
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			result.WriteRune(r + ('a' - 'A'))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
