package sdkgen

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"strings"

	"github.com/liyang/weave/pkg/types"
)

type goGenerator struct{}

func (g *goGenerator) Language() string { return "go" }

func (g *goGenerator) Generate(_ context.Context, schema OntologySchema) ([]GeneratedFile, error) {
	var files []GeneratedFile

	modName := fmt.Sprintf("weave-sdk/%s", schema.Ontology.APIName)

	models, err := g.generateModels(schema)
	if err != nil {
		return nil, fmt.Errorf("generate models: %w", err)
	}
	files = append(files, GeneratedFile{Path: "models.go", Content: models})

	client, err := g.generateClient(schema)
	if err != nil {
		return nil, fmt.Errorf("generate client: %w", err)
	}
	files = append(files, GeneratedFile{Path: "client.go", Content: client})

	files = append(files, GeneratedFile{Path: "go.mod", Content: g.generateGoMod(modName)})

	files = appendVersionFiles(files, schema, g.Language())
	return files, nil
}

func (g *goGenerator) generateModels(schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	buf.WriteString("package sdk\n\n")

	needsTime, needsJSON, needsGeoPoint := false, false, false
	for _, ot := range schema.ObjectTypes {
		for _, p := range ot.Properties {
			switch types.BaseType(p.BaseType) {
			case types.Timestamp:
				needsTime = true
			case types.Geoshape:
				needsJSON = true
			case types.Geopoint:
				needsGeoPoint = true
			}
		}
	}

	if needsTime || needsJSON {
		buf.WriteString("import (\n")
		if needsJSON {
			buf.WriteString("\t\"encoding/json\"\n")
		}
		if needsTime {
			buf.WriteString("\t\"time\"\n")
		}
		buf.WriteString(")\n\n")
	}

	if needsGeoPoint {
		buf.WriteString("// GeoPoint represents a geographic coordinate.\n")
		buf.WriteString("type GeoPoint struct {\n")
		buf.WriteString("\tLat float64 `json:\"lat\"`\n")
		buf.WriteString("\tLon float64 `json:\"lon\"`\n")
		buf.WriteString("}\n\n")
	}

	for _, ot := range schema.ObjectTypes {
		displayName := ot.DisplayName
		if displayName == "" {
			displayName = ot.APIName
		}
		fmt.Fprintf(&buf, "// %s represents a %s object.\n", ot.APIName, displayName)
		fmt.Fprintf(&buf, "type %s struct {\n", ot.APIName)
		for _, p := range ot.Properties {
			goType := resolveGoType(p.BaseType, p.IsArray)
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", exportedFieldName(p.APIName), goType, p.APIName)
		}
		buf.WriteString("}\n\n")
	}

	for _, at := range schema.ActionTypes {
		if len(at.Parameters) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "// %sParams holds parameters for the %s action.\n", pascalCase(at.APIName), at.APIName)
		fmt.Fprintf(&buf, "type %sParams struct {\n", pascalCase(at.APIName))
		for _, p := range at.Parameters {
			goType := resolveGoType(p.BaseType, false)
			if !p.Required {
				goType = "*" + goType
			}
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", exportedFieldName(p.ID), goType, p.ID)
		}
		buf.WriteString("}\n\n")
	}

	if needsJSON {
		buf.WriteString("var _ json.RawMessage\n")
	}
	if needsTime {
		buf.WriteString("var _ time.Time\n")
	}

	return format.Source(buf.Bytes())
}

func (g *goGenerator) generateClient(schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	buf.WriteString("package sdk\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(`// ListOptions configures pagination for list/search requests.
type ListOptions struct {
	PageSize  int
	PageToken string
}

// ListResult is the paginated response envelope returned by list/search endpoints.
type ListResult[T any] struct {
	Data          []T    ` + "`json:\"data\"`" + `
	NextPageToken string ` + "`json:\"nextPageToken,omitempty\"`" + `
}

// RoundTripFunc is the inner step of the middleware chain.
type RoundTripFunc func(*http.Request) (*http.Response, error)

// Middleware wraps the request pipeline. Implementations receive the prepared
// *http.Request plus the next handler; they may inspect / mutate the request,
// short-circuit by returning a synthetic response, or transform the response on
// the way back. Typical uses: auth header injection, structured logging, retry,
// telemetry.
type Middleware func(req *http.Request, next RoundTripFunc) (*http.Response, error)

// Client is the Weave SDK client.
type Client struct {
	BaseURL     string
	Ontology    string
	Token       string
	HTTP        *http.Client
	middlewares []Middleware
}

// NewClient constructs a Client with sensible defaults.
func NewClient(baseURL, ontology, token string) *Client {
	return &Client{BaseURL: baseURL, Ontology: ontology, Token: token, HTTP: http.DefaultClient}
}

// Use registers a middleware. The first middleware registered ends up at the
// OUTERMOST layer of the chain — it sees the original request first and the
// final response last.
func (c *Client) Use(mw Middleware) {
	c.middlewares = append(c.middlewares, mw)
}

func (c *Client) do(ctx context.Context, method, path string, body, out interface{}) error {
	var reqBody *bytes.Buffer
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reqBody = bytes.NewBuffer(b)
	}
	var req *http.Request
	var err error
	if reqBody != nil {
		req, err = http.NewRequestWithContext(ctx, method, c.BaseURL+path, reqBody)
	} else {
		req, err = http.NewRequestWithContext(ctx, method, c.BaseURL+path, nil)
	}
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	httpClient := c.HTTP
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	next := RoundTripFunc(func(r *http.Request) (*http.Response, error) {
		return httpClient.Do(r)
	})
	for i := len(c.middlewares) - 1; i >= 0; i-- {
		mw := c.middlewares[i]
		prev := next
		next = func(r *http.Request) (*http.Response, error) {
			return mw(r, prev)
		}
	}
	resp, err := next(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("weave API error: %d", resp.StatusCode)
	}
	if out != nil {
		return json.NewDecoder(resp.Body).Decode(out)
	}
	return nil
}

func appendListQuery(path string, opts *ListOptions) string {
	if opts == nil {
		return path
	}
	q := url.Values{}
	if opts.PageSize > 0 {
		q.Set("pageSize", fmt.Sprintf("%d", opts.PageSize))
	}
	if opts.PageToken != "" {
		q.Set("pageToken", opts.PageToken)
	}
	if encoded := q.Encode(); encoded != "" {
		return path + "?" + encoded
	}
	return path
}

`)

	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "// Get%s fetches an %s by primary key.\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "func (c *Client) Get%s(ctx context.Context, pk string) (*%s, error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tvar out %s\n", ot.APIName)
		fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s/%%s\", url.PathEscape(c.Ontology), url.PathEscape(pk))\n", ot.APIName)
		buf.WriteString("\tif err := c.do(ctx, \"GET\", path, nil, &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &out, nil\n")
		buf.WriteString("}\n\n")

		fmt.Fprintf(&buf, "// List%s paginates over %s objects.\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "func (c *Client) List%s(ctx context.Context, opts *ListOptions) (*ListResult[%s], error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tpath := appendListQuery(fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s\", url.PathEscape(c.Ontology)), opts)\n", ot.APIName)
		fmt.Fprintf(&buf, "\tvar out ListResult[%s]\n", ot.APIName)
		buf.WriteString("\tif err := c.do(ctx, \"GET\", path, nil, &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &out, nil\n")
		buf.WriteString("}\n\n")

		fmt.Fprintf(&buf, "// Search%s searches %s objects using the given where clause.\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "func (c *Client) Search%s(ctx context.Context, where map[string]interface{}, opts *ListOptions) (*ListResult[%s], error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s/search\", url.PathEscape(c.Ontology))\n", ot.APIName)
		buf.WriteString("\tbody := map[string]interface{}{\"where\": where}\n")
		buf.WriteString("\tif opts != nil {\n")
		buf.WriteString("\t\tif opts.PageSize > 0 {\n")
		buf.WriteString("\t\t\tbody[\"pageSize\"] = opts.PageSize\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tif opts.PageToken != \"\" {\n")
		buf.WriteString("\t\t\tbody[\"pageToken\"] = opts.PageToken\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t}\n")
		fmt.Fprintf(&buf, "\tvar out ListResult[%s]\n", ot.APIName)
		buf.WriteString("\tif err := c.do(ctx, \"POST\", path, body, &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &out, nil\n")
		buf.WriteString("}\n\n")
	}

	for _, at := range schema.ActionTypes {
		method := "Apply" + pascalCase(at.APIName)
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "// %s applies the %s action.\n", method, at.APIName)
			fmt.Fprintf(&buf, "func (c *Client) %s(ctx context.Context, params %sParams) error {\n", method, pascalCase(at.APIName))
			fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/actions/%s/apply\", url.PathEscape(c.Ontology))\n", at.APIName)
			buf.WriteString("\treturn c.do(ctx, \"POST\", path, map[string]interface{}{\"parameters\": params}, nil)\n")
		} else {
			fmt.Fprintf(&buf, "// %s applies the %s action.\n", method, at.APIName)
			fmt.Fprintf(&buf, "func (c *Client) %s(ctx context.Context) error {\n", method)
			fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/actions/%s/apply\", url.PathEscape(c.Ontology))\n", at.APIName)
			buf.WriteString("\treturn c.do(ctx, \"POST\", path, nil, nil)\n")
		}
		buf.WriteString("}\n\n")
	}

	return format.Source(buf.Bytes())
}

func (g *goGenerator) generateGoMod(modName string) []byte {
	return []byte(fmt.Sprintf("module %s\n\ngo 1.21\n", modName))
}

func resolveGoType(baseType string, isArray bool) string {
	mapped, ok := goTypeMap[types.BaseType(baseType)]
	if !ok {
		mapped = "interface{}"
	}
	if isArray {
		return "[]" + mapped
	}
	return mapped
}

// exportedFieldName converts a camelCase API name to an exported Go field name.
// Trailing "Id" is rewritten to "ID" per Go's initialism convention.
func exportedFieldName(name string) string {
	if name == "" {
		return name
	}
	upper := strings.ToUpper(name[:1]) + name[1:]
	if strings.HasSuffix(upper, "Id") {
		upper = upper[:len(upper)-2] + "ID"
	}
	return upper
}
