package sdkgen

import (
	"bytes"
	"context"
	"fmt"
	"strings"

	"github.com/liyang/weave/pkg/types"
)

type goGenerator struct{}

func (g *goGenerator) Language() string { return "go" }

func (g *goGenerator) Generate(_ context.Context, schema OntologySchema) ([]GeneratedFile, error) {
	var files []GeneratedFile

	modName := fmt.Sprintf("weave-sdk/%s", schema.Ontology.APIName)

	// models.go — one struct per ObjectType
	models, err := g.generateModels(schema, modName)
	if err != nil {
		return nil, fmt.Errorf("generate models: %w", err)
	}
	files = append(files, GeneratedFile{Path: "models.go", Content: models})

	// client.go
	client, err := g.generateClient(schema, modName)
	if err != nil {
		return nil, fmt.Errorf("generate client: %w", err)
	}
	files = append(files, GeneratedFile{Path: "client.go", Content: client})

	// go.mod
	gomod := g.generateGoMod(modName)
	files = append(files, GeneratedFile{Path: "go.mod", Content: gomod})

	return files, nil
}

func (g *goGenerator) generateModels(schema OntologySchema, _ string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	buf.WriteString("package sdk\n\n")

	needsTime := false
	needsJSON := false
	for _, ot := range schema.ObjectTypes {
		for _, p := range ot.Properties {
			bt := types.BaseType(p.BaseType)
			if bt == types.Timestamp {
				needsTime = true
			}
			if bt == types.Geoshape {
				needsJSON = true
			}
		}
	}

	if needsTime || needsJSON {
		buf.WriteString("import (\n")
		if needsJSON {
			buf.WriteString("\t\"encoding/json\"\n")
		}
		if needsTime {
			buf.WriteString("\t\"time\"\n")
		}
		buf.WriteString(")\n\n")
	}

	// GeoPoint helper if needed
	for _, ot := range schema.ObjectTypes {
		for _, p := range ot.Properties {
			if types.BaseType(p.BaseType) == types.Geopoint {
				buf.WriteString("// GeoPoint represents a geographic coordinate.\n")
				buf.WriteString("type GeoPoint struct {\n")
				buf.WriteString("\tLat float64 `json:\"lat\"`\n")
				buf.WriteString("\tLon float64 `json:\"lon\"`\n")
				buf.WriteString("}\n\n")
				goto doneGeo
			}
		}
	}
doneGeo:

	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "// %s represents a %s object.\n", ot.APIName, ot.DisplayName)
		fmt.Fprintf(&buf, "type %s struct {\n", ot.APIName)
		for _, p := range ot.Properties {
			goType := resolveGoType(p.BaseType, p.IsArray)
			jsonTag := p.APIName
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", exportedFieldName(p.APIName), goType, jsonTag)
		}
		buf.WriteString("}\n\n")
	}

	// Action parameter structs
	for _, at := range schema.ActionTypes {
		if len(at.Parameters) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "// %sParams holds parameters for the %s action.\n", pascalCase(at.APIName), at.APIName)
		fmt.Fprintf(&buf, "type %sParams struct {\n", pascalCase(at.APIName))
		for _, p := range at.Parameters {
			goType := resolveGoType(p.BaseType, false)
			if !p.Required {
				goType = "*" + goType
			}
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", exportedFieldName(p.ID), goType, p.ID)
		}
		buf.WriteString("}\n\n")
	}

	// Suppress unused import warnings
	if needsJSON {
		buf.WriteString("var _ json.RawMessage\n")
	}
	if needsTime {
		buf.WriteString("var _ time.Time\n")
	}

	return buf.Bytes(), nil
}

func (g *goGenerator) generateClient(schema OntologySchema, _ string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	buf.WriteString("package sdk\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// Client is the Weave SDK client.\n")
	buf.WriteString("type Client struct {\n")
	buf.WriteString("\tBaseURL  string\n")
	buf.WriteString("\tOntology string\n")
	buf.WriteString("\tToken    string\n")
	buf.WriteString("\tHTTP     *http.Client\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (c *Client) do(ctx context.Context, method, path string, body, out interface{}) error {\n")
	buf.WriteString("\tvar reqBody *bytes.Buffer\n")
	buf.WriteString("\tif body != nil {\n")
	buf.WriteString("\t\tb, err := json.Marshal(body)\n")
	buf.WriteString("\t\tif err != nil {\n")
	buf.WriteString("\t\t\treturn err\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\treqBody = bytes.NewBuffer(b)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tvar r *http.Request\n")
	buf.WriteString("\tvar err error\n")
	buf.WriteString("\tif reqBody != nil {\n")
	buf.WriteString("\t\tr, err = http.NewRequestWithContext(ctx, method, c.BaseURL+path, reqBody)\n")
	buf.WriteString("\t} else {\n")
	buf.WriteString("\t\tr, err = http.NewRequestWithContext(ctx, method, c.BaseURL+path, nil)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn err\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tr.Header.Set(\"Content-Type\", \"application/json\")\n")
	buf.WriteString("\tif c.Token != \"\" {\n")
	buf.WriteString("\t\tr.Header.Set(\"Authorization\", \"Bearer \"+c.Token)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\thttpClient := c.HTTP\n")
	buf.WriteString("\tif httpClient == nil {\n")
	buf.WriteString("\t\thttpClient = http.DefaultClient\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tresp, err := httpClient.Do(r)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn err\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n")
	buf.WriteString("\tif resp.StatusCode >= 400 {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"weave API error: %d\", resp.StatusCode)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif out != nil {\n")
	buf.WriteString("\t\treturn json.NewDecoder(resp.Body).Decode(out)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "func (c *Client) Get%s(ctx context.Context, pk string) (*%s, error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tvar out %s\n", ot.APIName)
		fmt.Fprintf(&buf, "\terr := c.do(ctx, \"GET\", fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s/%%s\", c.Ontology, pk), nil, &out)\n", ot.APIName)
		buf.WriteString("\treturn &out, err\n")
		buf.WriteString("}\n\n")

		fmt.Fprintf(&buf, "func (c *Client) List%s(ctx context.Context) ([]%s, error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tvar out struct{ Data []%s `json:\"data\"` }\n", ot.APIName)
		fmt.Fprintf(&buf, "\terr := c.do(ctx, \"GET\", fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s\", c.Ontology), nil, &out)\n", ot.APIName)
		buf.WriteString("\treturn out.Data, err\n")
		buf.WriteString("}\n\n")
	}

	for _, at := range schema.ActionTypes {
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "func (c *Client) Apply%s(ctx context.Context, params %sParams) error {\n", pascalCase(at.APIName), pascalCase(at.APIName))
			fmt.Fprintf(&buf, "\treturn c.do(ctx, \"POST\", fmt.Sprintf(\"/api/v2/ontologies/%%s/actions/%s/apply\", c.Ontology), map[string]interface{}{\"parameters\": params}, nil)\n", at.APIName)
		} else {
			fmt.Fprintf(&buf, "func (c *Client) Apply%s(ctx context.Context) error {\n", pascalCase(at.APIName))
			fmt.Fprintf(&buf, "\treturn c.do(ctx, \"POST\", fmt.Sprintf(\"/api/v2/ontologies/%%s/actions/%s/apply\", c.Ontology), nil, nil)\n", at.APIName)
		}
		buf.WriteString("}\n\n")
	}

	return buf.Bytes(), nil
}

func (g *goGenerator) generateGoMod(modName string) []byte {
	return []byte(fmt.Sprintf("module %s\n\ngo 1.21\n", modName))
}

func resolveGoType(baseType string, isArray bool) string {
	mapped, ok := goTypeMap[types.BaseType(baseType)]
	if !ok {
		mapped = "interface{}"
	}
	if isArray {
		return "[]" + mapped
	}
	return mapped
}

// exportedFieldName converts a camelCase API name to an exported Go field name.
func exportedFieldName(name string) string {
	if name == "" {
		return name
	}
	// Handle common ID suffixes
	upper := strings.ToUpper(name[:1]) + name[1:]
	upper = strings.ReplaceAll(upper, "Id", "ID")
	return upper
}
