package sdkgen

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"path"
	"strings"

	"github.com/liyang/weave/pkg/types"
)

type goGenerator struct{}

func (g *goGenerator) Language() string { return "go" }

// Generate emits the SDK in the per-ontology layout required by US-420:
//
//	go.mod                          (root)
//	pkg/<ontology>/client.go        (Client + middleware/retry/telemetry + ListOptions/ListResult)
//	pkg/<ontology>/objects.go       (object structs + per-type Get/List/Search + linkedObjects)
//	pkg/<ontology>/actions.go       (action param structs + Apply<Action> methods)
//	pkg/<ontology>/functions.go     (per-Function Execute<Name> wrappers + generic ExecuteFunction)
//	examples/telemetry_otel.go      (OpenTelemetry-style instrumenter, build-tagged ignore)
//	.weave-sdk.json + CHANGELOG.md  (via appendVersionFiles)
func (g *goGenerator) Generate(_ context.Context, schema OntologySchema) ([]GeneratedFile, error) {
	pkgName := goPackageName(schema.Ontology.APIName)
	modName := fmt.Sprintf("weave-sdk/%s", schema.Ontology.APIName)
	pkgDir := path.Join("pkg", pkgName)
	pkgImportPath := fmt.Sprintf("%s/%s", modName, pkgDir)

	var files []GeneratedFile

	client, err := g.generateClient(pkgName, schema)
	if err != nil {
		return nil, fmt.Errorf("generate client: %w", err)
	}
	files = append(files, GeneratedFile{Path: path.Join(pkgDir, "client.go"), Content: client})

	objects, err := g.generateObjects(pkgName, schema)
	if err != nil {
		return nil, fmt.Errorf("generate objects: %w", err)
	}
	files = append(files, GeneratedFile{Path: path.Join(pkgDir, "objects.go"), Content: objects})

	actions, err := g.generateActions(pkgName, schema)
	if err != nil {
		return nil, fmt.Errorf("generate actions: %w", err)
	}
	files = append(files, GeneratedFile{Path: path.Join(pkgDir, "actions.go"), Content: actions})

	functions, err := g.generateFunctions(pkgName, schema)
	if err != nil {
		return nil, fmt.Errorf("generate functions: %w", err)
	}
	files = append(files, GeneratedFile{Path: path.Join(pkgDir, "functions.go"), Content: functions})

	files = append(files, GeneratedFile{Path: "go.mod", Content: g.generateGoMod(modName)})

	example, err := g.generateTelemetryExample(pkgImportPath, pkgName)
	if err != nil {
		return nil, fmt.Errorf("generate telemetry example: %w", err)
	}
	files = append(files, GeneratedFile{Path: "examples/telemetry_otel.go", Content: example})

	files = appendVersionFiles(files, schema, g.Language())
	return files, nil
}

func (g *goGenerator) generateObjects(pkgName string, schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	needsTime, needsJSON := false, false
	for _, ot := range schema.ObjectTypes {
		for _, p := range ot.Properties {
			switch types.BaseType(p.BaseType) {
			case types.Timestamp:
				needsTime = true
			case types.Geoshape:
				needsJSON = true
			}
		}
	}

	imports := []string{
		"\"context\"",
		"\"fmt\"",
		"\"net/url\"",
	}
	if needsJSON {
		imports = append(imports, "\"encoding/json\"")
	}
	if needsTime {
		imports = append(imports, "\"time\"")
	}
	buf.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(&buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")

	for _, ot := range schema.ObjectTypes {
		displayName := ot.DisplayName
		if displayName == "" {
			displayName = ot.APIName
		}
		fmt.Fprintf(&buf, "// %s represents a %s object.\n", ot.APIName, displayName)
		fmt.Fprintf(&buf, "type %s struct {\n", ot.APIName)
		for _, p := range ot.Properties {
			goType := resolveGoType(p.BaseType, p.IsArray)
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", exportedFieldName(p.APIName), goType, p.APIName)
		}
		buf.WriteString("}\n\n")
	}

	bySource := goLinksBySource(schema)

	for _, ot := range schema.ObjectTypes {
		fmt.Fprintf(&buf, "// Get%s fetches an %s by primary key.\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "func (c *Client) Get%s(ctx context.Context, pk string) (*%s, error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tvar out %s\n", ot.APIName)
		fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s/%%s\", url.PathEscape(c.Ontology), url.PathEscape(pk))\n", ot.APIName)
		buf.WriteString("\tif err := c.do(ctx, \"GET\", path, nil, &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &out, nil\n")
		buf.WriteString("}\n\n")

		fmt.Fprintf(&buf, "// List%s paginates over %s objects.\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "func (c *Client) List%s(ctx context.Context, opts *ListOptions) (*ListResult[%s], error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tpath := appendListQuery(fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s\", url.PathEscape(c.Ontology)), opts)\n", ot.APIName)
		fmt.Fprintf(&buf, "\tvar out ListResult[%s]\n", ot.APIName)
		buf.WriteString("\tif err := c.do(ctx, \"GET\", path, nil, &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &out, nil\n")
		buf.WriteString("}\n\n")

		fmt.Fprintf(&buf, "// Search%s searches %s objects using the given where clause.\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "func (c *Client) Search%s(ctx context.Context, where map[string]interface{}, opts *ListOptions) (*ListResult[%s], error) {\n", ot.APIName, ot.APIName)
		fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s/search\", url.PathEscape(c.Ontology))\n", ot.APIName)
		buf.WriteString("\tbody := map[string]interface{}{\"where\": where}\n")
		buf.WriteString("\tif opts != nil {\n")
		buf.WriteString("\t\tif opts.PageSize > 0 {\n")
		buf.WriteString("\t\t\tbody[\"pageSize\"] = opts.PageSize\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tif opts.PageToken != \"\" {\n")
		buf.WriteString("\t\t\tbody[\"pageToken\"] = opts.PageToken\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t}\n")
		fmt.Fprintf(&buf, "\tvar out ListResult[%s]\n", ot.APIName)
		buf.WriteString("\tif err := c.do(ctx, \"POST\", path, body, &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn &out, nil\n")
		buf.WriteString("}\n\n")

		for _, lt := range bySource[ot.APIName] {
			fmt.Fprintf(&buf, "// LinkedObjects%s%s traverses the %s link from a source %s primary key.\n",
				ot.APIName, pascalCase(lt.APIName), lt.APIName, ot.APIName)
			fmt.Fprintf(&buf, "func (c *Client) LinkedObjects%s%s(ctx context.Context, pk string) ([]%s, error) {\n",
				ot.APIName, pascalCase(lt.APIName), lt.TargetObjectType)
			fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/objects/%s/%%s/links/%s\", url.PathEscape(c.Ontology), url.PathEscape(pk))\n",
				lt.SourceObjectType, lt.APIName)
			fmt.Fprintf(&buf, "\tvar wrap struct{ Data []%s `json:\"data\"` }\n", lt.TargetObjectType)
			buf.WriteString("\tif err := c.do(ctx, \"GET\", path, nil, &wrap); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn wrap.Data, nil\n")
			buf.WriteString("}\n\n")
		}
	}

	if needsJSON {
		buf.WriteString("var _ json.RawMessage\n")
	}
	if needsTime {
		buf.WriteString("var _ time.Time\n")
	}

	return format.Source(buf.Bytes())
}

func (g *goGenerator) generateActions(pkgName string, schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString(")\n\n")

	for _, at := range schema.ActionTypes {
		if len(at.Parameters) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "// %sParams holds parameters for the %s action.\n", pascalCase(at.APIName), at.APIName)
		fmt.Fprintf(&buf, "type %sParams struct {\n", pascalCase(at.APIName))
		for _, p := range at.Parameters {
			goType := resolveGoType(p.BaseType, false)
			if !p.Required {
				goType = "*" + goType
			}
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s\"`\n", exportedFieldName(p.ID), goType, p.ID)
		}
		buf.WriteString("}\n\n")
	}

	for _, at := range schema.ActionTypes {
		method := "Apply" + pascalCase(at.APIName)
		if len(at.Parameters) > 0 {
			fmt.Fprintf(&buf, "// %s applies the %s action.\n", method, at.APIName)
			fmt.Fprintf(&buf, "func (c *Client) %s(ctx context.Context, params %sParams) error {\n", method, pascalCase(at.APIName))
			fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/actions/%s/apply\", url.PathEscape(c.Ontology))\n", at.APIName)
			buf.WriteString("\treturn c.do(ctx, \"POST\", path, map[string]interface{}{\"parameters\": params}, nil)\n")
		} else {
			fmt.Fprintf(&buf, "// %s applies the %s action.\n", method, at.APIName)
			fmt.Fprintf(&buf, "func (c *Client) %s(ctx context.Context) error {\n", method)
			fmt.Fprintf(&buf, "\tpath := fmt.Sprintf(\"/api/v2/ontologies/%%s/actions/%s/apply\", url.PathEscape(c.Ontology))\n", at.APIName)
			buf.WriteString("\treturn c.do(ctx, \"POST\", path, nil, nil)\n")
		}
		buf.WriteString("}\n\n")
	}

	if len(schema.ActionTypes) == 0 {
		// Keep imports referenced even when no actions are emitted so the file
		// still passes go vet. The compiler treats blank-identifier underscore
		// references as "use" without producing runtime overhead.
		buf.WriteString("var (\n")
		buf.WriteString("\t_ = context.Background\n")
		buf.WriteString("\t_ = fmt.Sprintf\n")
		buf.WriteString("\t_ = url.PathEscape\n")
		buf.WriteString(")\n")
	}

	return format.Source(buf.Bytes())
}

func (g *goGenerator) generateFunctions(pkgName string, schema OntologySchema) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(`// FunctionExecuteRequest is the wire body the server expects on
// POST /api/v2/ontologies/{ontology}/functions/{ref}/execute.
type FunctionExecuteRequest struct {
	Parameters map[string]interface{} ` + "`json:\"parameters,omitempty\"`" + `
}

// FunctionExecuteResponse is the wire envelope returned by the server.
// Result is left as a raw map so callers can either unmarshal it themselves or
// pass an out pointer to ExecuteFunction for typed decoding.
type FunctionExecuteResponse struct {
	Result map[string]interface{} ` + "`json:\"result\"`" + `
}

// ExecuteFunction is the generic wrapper for executing any Function by
// reference (rid, name, or name@version). It threads parameters through the
// canonical wire envelope and decodes the response into out, which may be nil
// to discard the result.
func (c *Client) ExecuteFunction(ctx context.Context, ref string, params map[string]interface{}, out interface{}) error {
	path := fmt.Sprintf("/api/v2/ontologies/%s/functions/%s/execute",
		url.PathEscape(c.Ontology), url.PathEscape(ref))
	body := FunctionExecuteRequest{Parameters: params}
	if out == nil {
		return c.do(ctx, "POST", path, body, nil)
	}
	return c.do(ctx, "POST", path, body, out)
}

`)

	for _, fn := range schema.Functions {
		ref := fn.Name
		if fn.Version != "" {
			ref = fn.Name + "@" + fn.Version
		}
		method := "Execute" + pascalCase(goSafeIdent(fn.Name))
		fmt.Fprintf(&buf, "// %s executes the %s Function (ref=%q).\n", method, fn.Name, ref)
		fmt.Fprintf(&buf, "func (c *Client) %s(ctx context.Context, params map[string]interface{}, out interface{}) error {\n", method)
		fmt.Fprintf(&buf, "\treturn c.ExecuteFunction(ctx, %q, params, out)\n", ref)
		buf.WriteString("}\n\n")
	}

	return format.Source(buf.Bytes())
}

func (g *goGenerator) generateClient(pkgName string, schema OntologySchema) ([]byte, error) {
	needsGeoPoint := false
	for _, ot := range schema.ObjectTypes {
		for _, p := range ot.Properties {
			if types.BaseType(p.BaseType) == types.Geopoint {
				needsGeoPoint = true
			}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by Weave SDK Generator — DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"errors\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"io\"\n")
	buf.WriteString("\t\"math\"\n")
	buf.WriteString("\t\"math/rand\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString("\t\"strconv\"\n")
	buf.WriteString("\t\"strings\"\n")
	buf.WriteString("\t\"time\"\n")
	buf.WriteString(")\n\n")

	if needsGeoPoint {
		buf.WriteString("// GeoPoint represents a geographic coordinate.\n")
		buf.WriteString("type GeoPoint struct {\n")
		buf.WriteString("\tLat float64 `json:\"lat\"`\n")
		buf.WriteString("\tLon float64 `json:\"lon\"`\n")
		buf.WriteString("}\n\n")
	}

	buf.WriteString(`// ListOptions configures pagination for list/search requests.
type ListOptions struct {
	PageSize  int
	PageToken string
}

// ListResult is the paginated response envelope returned by list/search endpoints.
type ListResult[T any] struct {
	Data          []T    ` + "`json:\"data\"`" + `
	NextPageToken string ` + "`json:\"nextPageToken,omitempty\"`" + `
}

// RoundTripFunc is the inner step of the middleware chain.
type RoundTripFunc func(*http.Request) (*http.Response, error)

// Middleware wraps the request pipeline. Implementations receive the prepared
// *http.Request plus the next handler; they may inspect / mutate the request,
// short-circuit by returning a synthetic response, or transform the response on
// the way back. Typical uses: auth header injection, structured logging, retry,
// telemetry.
type Middleware func(req *http.Request, next RoundTripFunc) (*http.Response, error)

// Client is the Weave SDK client.
type Client struct {
	BaseURL     string
	Ontology    string
	Token       string
	HTTP        *http.Client
	middlewares []Middleware
}

// NewClient constructs a Client with sensible defaults.
func NewClient(baseURL, ontology, token string) *Client {
	return &Client{BaseURL: baseURL, Ontology: ontology, Token: token, HTTP: http.DefaultClient}
}

// Use registers a middleware. The first middleware registered ends up at the
// OUTERMOST layer of the chain — it sees the original request first and the
// final response last.
func (c *Client) Use(mw Middleware) {
	c.middlewares = append(c.middlewares, mw)
}

// RetryPolicy configures the built-in retry middleware. The middleware retries
// only idempotent HTTP methods (GET / HEAD / OPTIONS / PUT / DELETE) on
// transport errors and on retriable status codes (408, 425, 429, 500, 502,
// 503, 504). Backoff is exponential with full jitter; if the server sends a
// Retry-After header (delta-seconds or HTTP-date) it overrides the computed
// delay so well-behaved clients yield to explicit guidance.
type RetryPolicy struct {
	// MaxAttempts is the total attempts INCLUDING the first try. Zero/negative
	// values fall back to 3 (i.e. up to 2 retries after the initial request).
	MaxAttempts int
	// BaseDelay is the initial backoff (exp 0). Zero falls back to 100ms.
	BaseDelay time.Duration
	// MaxDelay caps any single backoff window. Zero falls back to 5s.
	MaxDelay time.Duration
	// Multiplier between successive attempts. Zero falls back to 2.0.
	Multiplier float64
	// RetryStatuses overrides the default retriable HTTP status set.
	RetryStatuses []int
	// RetryMethods overrides the default idempotent method set.
	RetryMethods []string
	// Rand is the jitter source. Nil falls back to the package-default rng.
	Rand *rand.Rand
	// Sleep is the wait function. Nil falls back to time.Sleep so tests can
	// inject a no-op or capture the delays.
	Sleep func(time.Duration)
}

var defaultRetryStatuses = []int{408, 425, 429, 500, 502, 503, 504}
var defaultRetryMethods = []string{http.MethodGet, http.MethodHead, http.MethodOptions, http.MethodPut, http.MethodDelete}

func parseRetryAfter(h string, now time.Time) (time.Duration, bool) {
	h = strings.TrimSpace(h)
	if h == "" {
		return 0, false
	}
	if secs, err := strconv.Atoi(h); err == nil && secs >= 0 {
		return time.Duration(secs) * time.Second, true
	}
	if t, err := http.ParseTime(h); err == nil {
		d := t.Sub(now)
		if d < 0 {
			d = 0
		}
		return d, true
	}
	return 0, false
}

// RetryMiddleware builds a Middleware that auto-retries idempotent requests with
// exponential backoff and full jitter. Install it once on the client:
//
//	client.Use(sdk.RetryMiddleware(sdk.RetryPolicy{MaxAttempts: 5}))
//
// Non-idempotent methods (POST / PATCH) bypass retries — they may have already
// taken effect on the server, and replaying them silently risks double-writes.
// The middleware drains and closes intermediate response bodies so connections
// return to the pool cleanly.
func RetryMiddleware(policy RetryPolicy) Middleware {
	maxAttempts := policy.MaxAttempts
	if maxAttempts <= 0 {
		maxAttempts = 3
	}
	baseDelay := policy.BaseDelay
	if baseDelay <= 0 {
		baseDelay = 100 * time.Millisecond
	}
	maxDelay := policy.MaxDelay
	if maxDelay < baseDelay {
		maxDelay = 5 * time.Second
	}
	mult := policy.Multiplier
	if mult <= 0 {
		mult = 2.0
	}
	statuses := policy.RetryStatuses
	if len(statuses) == 0 {
		statuses = defaultRetryStatuses
	}
	statusSet := make(map[int]struct{}, len(statuses))
	for _, s := range statuses {
		statusSet[s] = struct{}{}
	}
	methods := policy.RetryMethods
	if len(methods) == 0 {
		methods = defaultRetryMethods
	}
	methodSet := make(map[string]struct{}, len(methods))
	for _, m := range methods {
		methodSet[strings.ToUpper(m)] = struct{}{}
	}
	rng := policy.Rand
	sleep := policy.Sleep
	if sleep == nil {
		sleep = time.Sleep
	}

	return func(req *http.Request, next RoundTripFunc) (*http.Response, error) {
		if _, ok := methodSet[strings.ToUpper(req.Method)]; !ok {
			return next(req)
		}
		var (
			lastErr  error
			lastResp *http.Response
			body     []byte
		)
		if req.Body != nil && req.GetBody == nil {
			b, err := io.ReadAll(req.Body)
			if err != nil {
				return nil, err
			}
			req.Body.Close()
			body = b
			req.Body = io.NopCloser(bytes.NewReader(body))
			req.GetBody = func() (io.ReadCloser, error) {
				return io.NopCloser(bytes.NewReader(body)), nil
			}
			req.ContentLength = int64(len(body))
		}
		for attempt := 0; attempt < maxAttempts; attempt++ {
			attemptReq := req
			if attempt > 0 && req.GetBody != nil {
				rc, err := req.GetBody()
				if err != nil {
					return nil, err
				}
				clone := req.Clone(req.Context())
				clone.Body = rc
				attemptReq = clone
			}
			resp, err := next(attemptReq)
			if err == nil {
				if _, retry := statusSet[resp.StatusCode]; !retry || attempt == maxAttempts-1 {
					return resp, nil
				}
				lastResp = resp
				lastErr = nil
			} else {
				if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
					return nil, err
				}
				if attempt == maxAttempts-1 {
					return nil, err
				}
				lastErr = err
				lastResp = nil
			}
			cap := time.Duration(math.Min(float64(maxDelay), float64(baseDelay)*math.Pow(mult, float64(attempt))))
			delay := jitter(rng, cap)
			if lastResp != nil {
				if d, ok := parseRetryAfter(lastResp.Header.Get("Retry-After"), time.Now()); ok {
					if d > maxDelay {
						d = maxDelay
					}
					delay = d
				}
				io.Copy(io.Discard, lastResp.Body)
				lastResp.Body.Close()
				lastResp = nil
			}
			sleep(delay)
		}
		if lastErr != nil {
			return nil, lastErr
		}
		return nil, fmt.Errorf("retry middleware: exhausted attempts")
	}
}

func jitter(rng *rand.Rand, cap time.Duration) time.Duration {
	if cap <= 0 {
		return 0
	}
	if rng != nil {
		return time.Duration(rng.Int63n(int64(cap) + 1))
	}
	return time.Duration(rand.Int63n(int64(cap) + 1))
}

// UseRetry installs the built-in retry middleware on this client.
func (c *Client) UseRetry(policy RetryPolicy) {
	c.Use(RetryMiddleware(policy))
}

// TelemetryHooks plugs OpenTelemetry-style instrumentation into the request
// pipeline. Every hook is optional; whatever OnRequest returns is threaded
// through to OnResponse / OnError so a single span (or any per-request value)
// can be carried across the call without per-call state. See
// examples/telemetry_otel.go for a complete OpenTelemetry wiring.
type TelemetryHooks struct {
	// OnRequest fires BEFORE the request is dispatched. Return a span / context /
	// opaque token; whatever you return is handed back to OnResponse / OnError.
	OnRequest func(req *http.Request) any
	// OnResponse fires AFTER the response is received (regardless of HTTP status).
	// span is the value previously returned from OnRequest, or nil.
	OnResponse func(req *http.Request, resp *http.Response, span any)
	// OnError fires when next() returns a non-nil error (transport error, ctx
	// canceled, etc).
	OnError func(req *http.Request, err error, span any)
}

// TelemetryMiddleware builds a Middleware that invokes the supplied hooks
// around each request. Install it once on the client:
//
//	client.Use(sdk.TelemetryMiddleware(hooks))
//
// Or use the sugar form c.UseTelemetry(hooks).
func TelemetryMiddleware(hooks TelemetryHooks) Middleware {
	return func(req *http.Request, next RoundTripFunc) (*http.Response, error) {
		var span any
		if hooks.OnRequest != nil {
			span = hooks.OnRequest(req)
		}
		resp, err := next(req)
		if err != nil {
			if hooks.OnError != nil {
				hooks.OnError(req, err, span)
			}
			return nil, err
		}
		if hooks.OnResponse != nil {
			hooks.OnResponse(req, resp, span)
		}
		return resp, nil
	}
}

// UseTelemetry installs the built-in telemetry middleware on this client.
// See examples/telemetry_otel.go for an OpenTelemetry instrumenter.
func (c *Client) UseTelemetry(hooks TelemetryHooks) {
	c.Use(TelemetryMiddleware(hooks))
}

func (c *Client) do(ctx context.Context, method, path string, body, out interface{}) error {
	var reqBody *bytes.Buffer
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reqBody = bytes.NewBuffer(b)
	}
	var req *http.Request
	var err error
	if reqBody != nil {
		req, err = http.NewRequestWithContext(ctx, method, c.BaseURL+path, reqBody)
	} else {
		req, err = http.NewRequestWithContext(ctx, method, c.BaseURL+path, nil)
	}
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	httpClient := c.HTTP
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	next := RoundTripFunc(func(r *http.Request) (*http.Response, error) {
		return httpClient.Do(r)
	})
	for i := len(c.middlewares) - 1; i >= 0; i-- {
		mw := c.middlewares[i]
		prev := next
		next = func(r *http.Request) (*http.Response, error) {
			return mw(r, prev)
		}
	}
	resp, err := next(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("weave API error: %d", resp.StatusCode)
	}
	if out != nil {
		return json.NewDecoder(resp.Body).Decode(out)
	}
	return nil
}

func appendListQuery(path string, opts *ListOptions) string {
	if opts == nil {
		return path
	}
	q := url.Values{}
	if opts.PageSize > 0 {
		q.Set("pageSize", fmt.Sprintf("%d", opts.PageSize))
	}
	if opts.PageToken != "" {
		q.Set("pageToken", opts.PageToken)
	}
	if encoded := q.Encode(); encoded != "" {
		return path + "?" + encoded
	}
	return path
}
`)

	return format.Source(buf.Bytes())
}

func (g *goGenerator) generateGoMod(modName string) []byte {
	return []byte(fmt.Sprintf("module %s\n\ngo 1.21\n", modName))
}

// generateTelemetryExample emits an OpenTelemetry-style example instrumenter
// at examples/telemetry_otel.go. The file is build-tagged `ignore` so it does
// not enter the SDK's regular build / vet path — users copy it into a real
// project, drop the build-ignore line, and replace the inline Tracer stub with
// the OpenTelemetry one. The import path resolves to the per-ontology subpackage
// (pkg/<ontology>) so downstream consumers see the same Client / TelemetryHooks
// types.
func (g *goGenerator) generateTelemetryExample(importPath, alias string) ([]byte, error) {
	src := fmt.Sprintf(goTelemetryExampleTmpl, alias, importPath, alias, alias, alias)
	return format.Source([]byte(src))
}

func resolveGoType(baseType string, isArray bool) string {
	mapped, ok := goTypeMap[types.BaseType(baseType)]
	if !ok {
		mapped = "interface{}"
	}
	if isArray {
		return "[]" + mapped
	}
	return mapped
}

// goLinksBySource groups link types by their source ObjectType apiName.
func goLinksBySource(schema OntologySchema) map[string][]LinkTypeSchema {
	out := make(map[string][]LinkTypeSchema)
	for _, lt := range schema.LinkTypes {
		out[lt.SourceObjectType] = append(out[lt.SourceObjectType], lt)
	}
	return out
}

// goTelemetryExampleTmpl is the source body of examples/telemetry_otel.go.
// It expects two %s substitutions: (1) the package alias used in the import
// (matching the SDK package name), and (2) the SDK's full import path (module
// path + /pkg/<ontology>). The build tag keeps the file out of normal builds
// so the example need not pull in OpenTelemetry as a real dependency — copy
// it into your project, drop the build-ignore line, and replace the stub
// Tracer with the OTel one.
const goTelemetryExampleTmpl = `//go:build ignore
// +build ignore

// Example: wire the Weave Go SDK telemetry hooks into OpenTelemetry.
//
// Replace the inline Tracer/Span stubs with go.opentelemetry.io/otel/api/trace
// in real use, then ` + "`client.UseTelemetry(otelHooks)`" + `.
package main

import (
	"fmt"
	"net/http"

	%s "%s"
)

type span interface {
	SetAttribute(key string, value any)
	RecordError(err error)
	End()
}

type tracer interface {
	StartSpan(name string, attrs map[string]any) span
}

type stubSpan struct{ name string }

func (s *stubSpan) SetAttribute(k string, v any) { fmt.Printf("[span:attr] %%s %%s=%%v\n", s.name, k, v) }
func (s *stubSpan) RecordError(err error)        { fmt.Printf("[span:err] %%s %%v\n", s.name, err) }
func (s *stubSpan) End()                         { fmt.Printf("[span:end] %%s\n", s.name) }

type stubTracer struct{}

func (stubTracer) StartSpan(name string, _ map[string]any) span { return &stubSpan{name: name} }

// Replace stubTracer{} with otel.Tracer("weave-sdk").
var tr tracer = stubTracer{}

func otelHooks() %s.TelemetryHooks {
	return %s.TelemetryHooks{
		OnRequest: func(req *http.Request) any {
			s := tr.StartSpan("weave.http_request", map[string]any{
				"http.method": req.Method,
				"http.url":    req.URL.String(),
			})
			return s
		},
		OnResponse: func(_ *http.Request, resp *http.Response, sp any) {
			s, ok := sp.(span)
			if !ok || s == nil {
				return
			}
			s.SetAttribute("http.status_code", resp.StatusCode)
			s.End()
		},
		OnError: func(_ *http.Request, err error, sp any) {
			s, ok := sp.(span)
			if !ok || s == nil {
				return
			}
			s.RecordError(err)
			s.End()
		},
	}
}

func main() {
	c := %s.NewClient("http://localhost:9117", "myOntology", "")
	c.UseTelemetry(otelHooks())
	_ = c
}
`

// exportedFieldName converts a camelCase API name to an exported Go field name.
// Trailing "Id" is rewritten to "ID" per Go's initialism convention.
func exportedFieldName(name string) string {
	if name == "" {
		return name
	}
	upper := strings.ToUpper(name[:1]) + name[1:]
	if strings.HasSuffix(upper, "Id") {
		upper = upper[:len(upper)-2] + "ID"
	}
	return upper
}

// goPackageName sanitises an ontology API name into a valid Go package
// identifier — lowercase letters / digits / underscores, leading digit
// prefixed with `_`. Empty input falls back to `weavesdk` so a degenerate
// schema still emits a parseable package declaration.
func goPackageName(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_':
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "weavesdk"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}

// goSafeIdent sanitises an arbitrary identifier (e.g. a Function name that
// may contain dots, hyphens, etc.) into a string that can flow into
// pascalCase to produce a valid Go method receiver name. Non-alphanumeric
// runes collapse into nothing; runs of letters/digits round-trip unchanged.
func goSafeIdent(s string) string {
	var b strings.Builder
	upperNext := false
	for i, r := range s {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'):
			if upperNext {
				if r >= 'a' && r <= 'z' {
					r = r - ('a' - 'A')
				}
				upperNext = false
			}
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteRune('_')
			}
			b.WriteRune(r)
		default:
			upperNext = true
		}
	}
	out := b.String()
	if out == "" {
		return "Function"
	}
	return out
}
